/**
 * @section license
 *
 * Copyright (c) 2006-2012 David Osborn
 *
 * Permission is granted to use and redistribute this software in source and
 * binary form, with or without modification, subject to the following
 * conditions:
 *
 * 1. Redistributions in source form must retain the above copyright notice,
 *    this list of conditions, and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions, and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution, and in the same
 *    place and form as other copyright, license, and disclaimer information.
 *
 * As a special exception, distributions of derivative works in binary form may
 * include an acknowledgement in place of the above copyright notice, this list
 * of conditions, and the following disclaimer in the documentation and/or other
 * materials provided with the distribution, and in the same place and form as
 * other acknowledgements, similar in substance to the following:
 *
 *    Portions of this software are based on the work of David Osborn.
 *
 * This software is provided "as is", without any express or implied warranty.
 * In no event will the authors be liable for any damages arising out of the use
 * of this software.
 */

#ifndef    page_local_err_exception_Exception_hpp
#   define page_local_err_exception_Exception_hpp

#	include "../../../thirdparty/loki/Typelist.h" // NoDuplicates
#	include "../../util/typelist.hpp" // MakeLokiTypelist
#	include "CatchableException.hpp"

namespace page
{
	namespace err
	{
		namespace detail
		{
			/**
			 * @defgroup BindTaggedException
			 * @{
			 */
			/**
			 * @class BindTaggedException
			 *
			 * Part of the implementation of @c Exception.
			 *
			 * This class inherits from @c CatchableException in every possible
			 * permutation of the tags.
			 *
			 * The permutations can be generated with the following Python
			 * program:
			 *
			 * @code
			 * import itertools
			 *
			 * L = ['A', 'B', 'C', 'D', 'E', 'F']
			 *
			 * def permutations(L):
			 * 	if len(L) > 2:
			 * 		result = []
			 * 		for i in range(len(L)):
			 * 			result.append(L[i:i + 1])
			 * 			for j in permutations(L[:i] + L[i + 1:]):
			 * 				result.append(L[i:i + 1] + j)
			 * 		return result
			 * 	else:
			 * 		return [L[0:1], L[1:2], L, list(reversed(L))]
			 *
			 * def format(L):
			 * 	return ["CatchableException<" + ("".join(itertools.repeat("{}, ", len(i) - 1)) + "{}>,").format(* i) for i in L]
			 *
			 * for line in sorted(format(permutations(L)), key=len):
			 * 	print(line)
			 * @endcode
			 */
			template <typename...>
				struct BindTaggedException;
			template <>
				struct BindTaggedException<> :
				CatchableException<>
			{
				BindTaggedException() {}
				explicit BindTaggedException(const std::string &what) :
					BasicException(what) {}
			};
			template <typename A>
				struct BindTaggedException<A> :
				CatchableException<>,
				CatchableException<A>
			{
				BindTaggedException() {}
				explicit BindTaggedException(const std::string &what) :
					BasicException(what) {}
			};
			template <typename A, typename B>
				struct BindTaggedException<A, B> :
				CatchableException<>,
				CatchableException<A>,
				CatchableException<B>,
				CatchableException<A, B>,
				CatchableException<B, A>
			{
				BindTaggedException() {}
				explicit BindTaggedException(const std::string &what) :
					BasicException(what) {}
			};
			template <typename A, typename B, typename C>
				struct BindTaggedException<A, B, C> :
				CatchableException<>,
				CatchableException<A>,
				CatchableException<B>,
				CatchableException<C>,
				CatchableException<A, B>,
				CatchableException<A, C>,
				CatchableException<B, A>,
				CatchableException<B, C>,
				CatchableException<C, A>,
				CatchableException<C, B>,
				CatchableException<A, B, C>,
				CatchableException<A, C, B>,
				CatchableException<B, A, C>,
				CatchableException<B, C, A>,
				CatchableException<C, A, B>,
				CatchableException<C, B, A>
			{
				BindTaggedException() {}
				explicit BindTaggedException(const std::string &what) :
					BasicException(what) {}
			};
			template <typename A, typename B, typename C, typename D>
				struct BindTaggedException<A, B, C, D> :
				CatchableException<>,
				CatchableException<A>,
				CatchableException<B>,
				CatchableException<C>,
				CatchableException<D>,
				CatchableException<A, B>,
				CatchableException<A, C>,
				CatchableException<A, D>,
				CatchableException<B, A>,
				CatchableException<B, C>,
				CatchableException<B, D>,
				CatchableException<C, A>,
				CatchableException<C, B>,
				CatchableException<C, D>,
				CatchableException<D, A>,
				CatchableException<D, B>,
				CatchableException<D, C>,
				CatchableException<A, B, C>,
				CatchableException<A, B, D>,
				CatchableException<A, C, B>,
				CatchableException<A, C, D>,
				CatchableException<A, D, B>,
				CatchableException<A, D, C>,
				CatchableException<B, A, C>,
				CatchableException<B, A, D>,
				CatchableException<B, C, A>,
				CatchableException<B, C, D>,
				CatchableException<B, D, A>,
				CatchableException<B, D, C>,
				CatchableException<C, A, B>,
				CatchableException<C, A, D>,
				CatchableException<C, B, A>,
				CatchableException<C, B, D>,
				CatchableException<C, D, A>,
				CatchableException<C, D, B>,
				CatchableException<D, A, B>,
				CatchableException<D, A, C>,
				CatchableException<D, B, A>,
				CatchableException<D, B, C>,
				CatchableException<D, C, A>,
				CatchableException<D, C, B>,
				CatchableException<A, B, C, D>,
				CatchableException<A, B, D, C>,
				CatchableException<A, C, B, D>,
				CatchableException<A, C, D, B>,
				CatchableException<A, D, B, C>,
				CatchableException<A, D, C, B>,
				CatchableException<B, A, C, D>,
				CatchableException<B, A, D, C>,
				CatchableException<B, C, A, D>,
				CatchableException<B, C, D, A>,
				CatchableException<B, D, A, C>,
				CatchableException<B, D, C, A>,
				CatchableException<C, A, B, D>,
				CatchableException<C, A, D, B>,
				CatchableException<C, B, A, D>,
				CatchableException<C, B, D, A>,
				CatchableException<C, D, A, B>,
				CatchableException<C, D, B, A>,
				CatchableException<D, A, B, C>,
				CatchableException<D, A, C, B>,
				CatchableException<D, B, A, C>,
				CatchableException<D, B, C, A>,
				CatchableException<D, C, A, B>,
				CatchableException<D, C, B, A>
			{
				BindTaggedException() {}
				explicit BindTaggedException(const std::string &what) :
					BasicException(what) {}
			};
			template <typename A, typename B, typename C, typename D, typename E>
				struct BindTaggedException<A, B, C, D, E> :
				CatchableException<>,
				CatchableException<A>,
				CatchableException<B>,
				CatchableException<C>,
				CatchableException<D>,
				CatchableException<E>,
				CatchableException<A, B>,
				CatchableException<A, C>,
				CatchableException<A, D>,
				CatchableException<A, E>,
				CatchableException<B, A>,
				CatchableException<B, C>,
				CatchableException<B, D>,
				CatchableException<B, E>,
				CatchableException<C, A>,
				CatchableException<C, B>,
				CatchableException<C, D>,
				CatchableException<C, E>,
				CatchableException<D, A>,
				CatchableException<D, B>,
				CatchableException<D, C>,
				CatchableException<D, E>,
				CatchableException<E, A>,
				CatchableException<E, B>,
				CatchableException<E, C>,
				CatchableException<E, D>,
				CatchableException<A, B, C>,
				CatchableException<A, B, D>,
				CatchableException<A, B, E>,
				CatchableException<A, C, B>,
				CatchableException<A, C, D>,
				CatchableException<A, C, E>,
				CatchableException<A, D, B>,
				CatchableException<A, D, C>,
				CatchableException<A, D, E>,
				CatchableException<A, E, B>,
				CatchableException<A, E, C>,
				CatchableException<A, E, D>,
				CatchableException<B, A, C>,
				CatchableException<B, A, D>,
				CatchableException<B, A, E>,
				CatchableException<B, C, A>,
				CatchableException<B, C, D>,
				CatchableException<B, C, E>,
				CatchableException<B, D, A>,
				CatchableException<B, D, C>,
				CatchableException<B, D, E>,
				CatchableException<B, E, A>,
				CatchableException<B, E, C>,
				CatchableException<B, E, D>,
				CatchableException<C, A, B>,
				CatchableException<C, A, D>,
				CatchableException<C, A, E>,
				CatchableException<C, B, A>,
				CatchableException<C, B, D>,
				CatchableException<C, B, E>,
				CatchableException<C, D, A>,
				CatchableException<C, D, B>,
				CatchableException<C, D, E>,
				CatchableException<C, E, A>,
				CatchableException<C, E, B>,
				CatchableException<C, E, D>,
				CatchableException<D, A, B>,
				CatchableException<D, A, C>,
				CatchableException<D, A, E>,
				CatchableException<D, B, A>,
				CatchableException<D, B, C>,
				CatchableException<D, B, E>,
				CatchableException<D, C, A>,
				CatchableException<D, C, B>,
				CatchableException<D, C, E>,
				CatchableException<D, E, A>,
				CatchableException<D, E, B>,
				CatchableException<D, E, C>,
				CatchableException<E, A, B>,
				CatchableException<E, A, C>,
				CatchableException<E, A, D>,
				CatchableException<E, B, A>,
				CatchableException<E, B, C>,
				CatchableException<E, B, D>,
				CatchableException<E, C, A>,
				CatchableException<E, C, B>,
				CatchableException<E, C, D>,
				CatchableException<E, D, A>,
				CatchableException<E, D, B>,
				CatchableException<E, D, C>,
				CatchableException<A, B, C, D>,
				CatchableException<A, B, C, E>,
				CatchableException<A, B, D, C>,
				CatchableException<A, B, D, E>,
				CatchableException<A, B, E, C>,
				CatchableException<A, B, E, D>,
				CatchableException<A, C, B, D>,
				CatchableException<A, C, B, E>,
				CatchableException<A, C, D, B>,
				CatchableException<A, C, D, E>,
				CatchableException<A, C, E, B>,
				CatchableException<A, C, E, D>,
				CatchableException<A, D, B, C>,
				CatchableException<A, D, B, E>,
				CatchableException<A, D, C, B>,
				CatchableException<A, D, C, E>,
				CatchableException<A, D, E, B>,
				CatchableException<A, D, E, C>,
				CatchableException<A, E, B, C>,
				CatchableException<A, E, B, D>,
				CatchableException<A, E, C, B>,
				CatchableException<A, E, C, D>,
				CatchableException<A, E, D, B>,
				CatchableException<A, E, D, C>,
				CatchableException<B, A, C, D>,
				CatchableException<B, A, C, E>,
				CatchableException<B, A, D, C>,
				CatchableException<B, A, D, E>,
				CatchableException<B, A, E, C>,
				CatchableException<B, A, E, D>,
				CatchableException<B, C, A, D>,
				CatchableException<B, C, A, E>,
				CatchableException<B, C, D, A>,
				CatchableException<B, C, D, E>,
				CatchableException<B, C, E, A>,
				CatchableException<B, C, E, D>,
				CatchableException<B, D, A, C>,
				CatchableException<B, D, A, E>,
				CatchableException<B, D, C, A>,
				CatchableException<B, D, C, E>,
				CatchableException<B, D, E, A>,
				CatchableException<B, D, E, C>,
				CatchableException<B, E, A, C>,
				CatchableException<B, E, A, D>,
				CatchableException<B, E, C, A>,
				CatchableException<B, E, C, D>,
				CatchableException<B, E, D, A>,
				CatchableException<B, E, D, C>,
				CatchableException<C, A, B, D>,
				CatchableException<C, A, B, E>,
				CatchableException<C, A, D, B>,
				CatchableException<C, A, D, E>,
				CatchableException<C, A, E, B>,
				CatchableException<C, A, E, D>,
				CatchableException<C, B, A, D>,
				CatchableException<C, B, A, E>,
				CatchableException<C, B, D, A>,
				CatchableException<C, B, D, E>,
				CatchableException<C, B, E, A>,
				CatchableException<C, B, E, D>,
				CatchableException<C, D, A, B>,
				CatchableException<C, D, A, E>,
				CatchableException<C, D, B, A>,
				CatchableException<C, D, B, E>,
				CatchableException<C, D, E, A>,
				CatchableException<C, D, E, B>,
				CatchableException<C, E, A, B>,
				CatchableException<C, E, A, D>,
				CatchableException<C, E, B, A>,
				CatchableException<C, E, B, D>,
				CatchableException<C, E, D, A>,
				CatchableException<C, E, D, B>,
				CatchableException<D, A, B, C>,
				CatchableException<D, A, B, E>,
				CatchableException<D, A, C, B>,
				CatchableException<D, A, C, E>,
				CatchableException<D, A, E, B>,
				CatchableException<D, A, E, C>,
				CatchableException<D, B, A, C>,
				CatchableException<D, B, A, E>,
				CatchableException<D, B, C, A>,
				CatchableException<D, B, C, E>,
				CatchableException<D, B, E, A>,
				CatchableException<D, B, E, C>,
				CatchableException<D, C, A, B>,
				CatchableException<D, C, A, E>,
				CatchableException<D, C, B, A>,
				CatchableException<D, C, B, E>,
				CatchableException<D, C, E, A>,
				CatchableException<D, C, E, B>,
				CatchableException<D, E, A, B>,
				CatchableException<D, E, A, C>,
				CatchableException<D, E, B, A>,
				CatchableException<D, E, B, C>,
				CatchableException<D, E, C, A>,
				CatchableException<D, E, C, B>,
				CatchableException<E, A, B, C>,
				CatchableException<E, A, B, D>,
				CatchableException<E, A, C, B>,
				CatchableException<E, A, C, D>,
				CatchableException<E, A, D, B>,
				CatchableException<E, A, D, C>,
				CatchableException<E, B, A, C>,
				CatchableException<E, B, A, D>,
				CatchableException<E, B, C, A>,
				CatchableException<E, B, C, D>,
				CatchableException<E, B, D, A>,
				CatchableException<E, B, D, C>,
				CatchableException<E, C, A, B>,
				CatchableException<E, C, A, D>,
				CatchableException<E, C, B, A>,
				CatchableException<E, C, B, D>,
				CatchableException<E, C, D, A>,
				CatchableException<E, C, D, B>,
				CatchableException<E, D, A, B>,
				CatchableException<E, D, A, C>,
				CatchableException<E, D, B, A>,
				CatchableException<E, D, B, C>,
				CatchableException<E, D, C, A>,
				CatchableException<E, D, C, B>,
				CatchableException<A, B, C, D, E>,
				CatchableException<A, B, C, E, D>,
				CatchableException<A, B, D, C, E>,
				CatchableException<A, B, D, E, C>,
				CatchableException<A, B, E, C, D>,
				CatchableException<A, B, E, D, C>,
				CatchableException<A, C, B, D, E>,
				CatchableException<A, C, B, E, D>,
				CatchableException<A, C, D, B, E>,
				CatchableException<A, C, D, E, B>,
				CatchableException<A, C, E, B, D>,
				CatchableException<A, C, E, D, B>,
				CatchableException<A, D, B, C, E>,
				CatchableException<A, D, B, E, C>,
				CatchableException<A, D, C, B, E>,
				CatchableException<A, D, C, E, B>,
				CatchableException<A, D, E, B, C>,
				CatchableException<A, D, E, C, B>,
				CatchableException<A, E, B, C, D>,
				CatchableException<A, E, B, D, C>,
				CatchableException<A, E, C, B, D>,
				CatchableException<A, E, C, D, B>,
				CatchableException<A, E, D, B, C>,
				CatchableException<A, E, D, C, B>,
				CatchableException<B, A, C, D, E>,
				CatchableException<B, A, C, E, D>,
				CatchableException<B, A, D, C, E>,
				CatchableException<B, A, D, E, C>,
				CatchableException<B, A, E, C, D>,
				CatchableException<B, A, E, D, C>,
				CatchableException<B, C, A, D, E>,
				CatchableException<B, C, A, E, D>,
				CatchableException<B, C, D, A, E>,
				CatchableException<B, C, D, E, A>,
				CatchableException<B, C, E, A, D>,
				CatchableException<B, C, E, D, A>,
				CatchableException<B, D, A, C, E>,
				CatchableException<B, D, A, E, C>,
				CatchableException<B, D, C, A, E>,
				CatchableException<B, D, C, E, A>,
				CatchableException<B, D, E, A, C>,
				CatchableException<B, D, E, C, A>,
				CatchableException<B, E, A, C, D>,
				CatchableException<B, E, A, D, C>,
				CatchableException<B, E, C, A, D>,
				CatchableException<B, E, C, D, A>,
				CatchableException<B, E, D, A, C>,
				CatchableException<B, E, D, C, A>,
				CatchableException<C, A, B, D, E>,
				CatchableException<C, A, B, E, D>,
				CatchableException<C, A, D, B, E>,
				CatchableException<C, A, D, E, B>,
				CatchableException<C, A, E, B, D>,
				CatchableException<C, A, E, D, B>,
				CatchableException<C, B, A, D, E>,
				CatchableException<C, B, A, E, D>,
				CatchableException<C, B, D, A, E>,
				CatchableException<C, B, D, E, A>,
				CatchableException<C, B, E, A, D>,
				CatchableException<C, B, E, D, A>,
				CatchableException<C, D, A, B, E>,
				CatchableException<C, D, A, E, B>,
				CatchableException<C, D, B, A, E>,
				CatchableException<C, D, B, E, A>,
				CatchableException<C, D, E, A, B>,
				CatchableException<C, D, E, B, A>,
				CatchableException<C, E, A, B, D>,
				CatchableException<C, E, A, D, B>,
				CatchableException<C, E, B, A, D>,
				CatchableException<C, E, B, D, A>,
				CatchableException<C, E, D, A, B>,
				CatchableException<C, E, D, B, A>,
				CatchableException<D, A, B, C, E>,
				CatchableException<D, A, B, E, C>,
				CatchableException<D, A, C, B, E>,
				CatchableException<D, A, C, E, B>,
				CatchableException<D, A, E, B, C>,
				CatchableException<D, A, E, C, B>,
				CatchableException<D, B, A, C, E>,
				CatchableException<D, B, A, E, C>,
				CatchableException<D, B, C, A, E>,
				CatchableException<D, B, C, E, A>,
				CatchableException<D, B, E, A, C>,
				CatchableException<D, B, E, C, A>,
				CatchableException<D, C, A, B, E>,
				CatchableException<D, C, A, E, B>,
				CatchableException<D, C, B, A, E>,
				CatchableException<D, C, B, E, A>,
				CatchableException<D, C, E, A, B>,
				CatchableException<D, C, E, B, A>,
				CatchableException<D, E, A, B, C>,
				CatchableException<D, E, A, C, B>,
				CatchableException<D, E, B, A, C>,
				CatchableException<D, E, B, C, A>,
				CatchableException<D, E, C, A, B>,
				CatchableException<D, E, C, B, A>,
				CatchableException<E, A, B, C, D>,
				CatchableException<E, A, B, D, C>,
				CatchableException<E, A, C, B, D>,
				CatchableException<E, A, C, D, B>,
				CatchableException<E, A, D, B, C>,
				CatchableException<E, A, D, C, B>,
				CatchableException<E, B, A, C, D>,
				CatchableException<E, B, A, D, C>,
				CatchableException<E, B, C, A, D>,
				CatchableException<E, B, C, D, A>,
				CatchableException<E, B, D, A, C>,
				CatchableException<E, B, D, C, A>,
				CatchableException<E, C, A, B, D>,
				CatchableException<E, C, A, D, B>,
				CatchableException<E, C, B, A, D>,
				CatchableException<E, C, B, D, A>,
				CatchableException<E, C, D, A, B>,
				CatchableException<E, C, D, B, A>,
				CatchableException<E, D, A, B, C>,
				CatchableException<E, D, A, C, B>,
				CatchableException<E, D, B, A, C>,
				CatchableException<E, D, B, C, A>,
				CatchableException<E, D, C, A, B>,
				CatchableException<E, D, C, B, A>
			{
				BindTaggedException() {}
				explicit BindTaggedException(const std::string &what) :
					BasicException(what) {}
			};
			template <typename A, typename B, typename C, typename D, typename E, typename F>
				struct BindTaggedException<A, B, C, D, E, F> :
				CatchableException<>,
				CatchableException<A>,
				CatchableException<B>,
				CatchableException<C>,
				CatchableException<D>,
				CatchableException<E>,
				CatchableException<F>,
				CatchableException<A, B>,
				CatchableException<A, C>,
				CatchableException<A, D>,
				CatchableException<A, E>,
				CatchableException<A, F>,
				CatchableException<B, A>,
				CatchableException<B, C>,
				CatchableException<B, D>,
				CatchableException<B, E>,
				CatchableException<B, F>,
				CatchableException<C, A>,
				CatchableException<C, B>,
				CatchableException<C, D>,
				CatchableException<C, E>,
				CatchableException<C, F>,
				CatchableException<D, A>,
				CatchableException<D, B>,
				CatchableException<D, C>,
				CatchableException<D, E>,
				CatchableException<D, F>,
				CatchableException<E, A>,
				CatchableException<E, B>,
				CatchableException<E, C>,
				CatchableException<E, D>,
				CatchableException<E, F>,
				CatchableException<F, A>,
				CatchableException<F, B>,
				CatchableException<F, C>,
				CatchableException<F, D>,
				CatchableException<F, E>,
				CatchableException<A, B, C>,
				CatchableException<A, B, D>,
				CatchableException<A, B, E>,
				CatchableException<A, B, F>,
				CatchableException<A, C, B>,
				CatchableException<A, C, D>,
				CatchableException<A, C, E>,
				CatchableException<A, C, F>,
				CatchableException<A, D, B>,
				CatchableException<A, D, C>,
				CatchableException<A, D, E>,
				CatchableException<A, D, F>,
				CatchableException<A, E, B>,
				CatchableException<A, E, C>,
				CatchableException<A, E, D>,
				CatchableException<A, E, F>,
				CatchableException<A, F, B>,
				CatchableException<A, F, C>,
				CatchableException<A, F, D>,
				CatchableException<A, F, E>,
				CatchableException<B, A, C>,
				CatchableException<B, A, D>,
				CatchableException<B, A, E>,
				CatchableException<B, A, F>,
				CatchableException<B, C, A>,
				CatchableException<B, C, D>,
				CatchableException<B, C, E>,
				CatchableException<B, C, F>,
				CatchableException<B, D, A>,
				CatchableException<B, D, C>,
				CatchableException<B, D, E>,
				CatchableException<B, D, F>,
				CatchableException<B, E, A>,
				CatchableException<B, E, C>,
				CatchableException<B, E, D>,
				CatchableException<B, E, F>,
				CatchableException<B, F, A>,
				CatchableException<B, F, C>,
				CatchableException<B, F, D>,
				CatchableException<B, F, E>,
				CatchableException<C, A, B>,
				CatchableException<C, A, D>,
				CatchableException<C, A, E>,
				CatchableException<C, A, F>,
				CatchableException<C, B, A>,
				CatchableException<C, B, D>,
				CatchableException<C, B, E>,
				CatchableException<C, B, F>,
				CatchableException<C, D, A>,
				CatchableException<C, D, B>,
				CatchableException<C, D, E>,
				CatchableException<C, D, F>,
				CatchableException<C, E, A>,
				CatchableException<C, E, B>,
				CatchableException<C, E, D>,
				CatchableException<C, E, F>,
				CatchableException<C, F, A>,
				CatchableException<C, F, B>,
				CatchableException<C, F, D>,
				CatchableException<C, F, E>,
				CatchableException<D, A, B>,
				CatchableException<D, A, C>,
				CatchableException<D, A, E>,
				CatchableException<D, A, F>,
				CatchableException<D, B, A>,
				CatchableException<D, B, C>,
				CatchableException<D, B, E>,
				CatchableException<D, B, F>,
				CatchableException<D, C, A>,
				CatchableException<D, C, B>,
				CatchableException<D, C, E>,
				CatchableException<D, C, F>,
				CatchableException<D, E, A>,
				CatchableException<D, E, B>,
				CatchableException<D, E, C>,
				CatchableException<D, E, F>,
				CatchableException<D, F, A>,
				CatchableException<D, F, B>,
				CatchableException<D, F, C>,
				CatchableException<D, F, E>,
				CatchableException<E, A, B>,
				CatchableException<E, A, C>,
				CatchableException<E, A, D>,
				CatchableException<E, A, F>,
				CatchableException<E, B, A>,
				CatchableException<E, B, C>,
				CatchableException<E, B, D>,
				CatchableException<E, B, F>,
				CatchableException<E, C, A>,
				CatchableException<E, C, B>,
				CatchableException<E, C, D>,
				CatchableException<E, C, F>,
				CatchableException<E, D, A>,
				CatchableException<E, D, B>,
				CatchableException<E, D, C>,
				CatchableException<E, D, F>,
				CatchableException<E, F, A>,
				CatchableException<E, F, B>,
				CatchableException<E, F, C>,
				CatchableException<E, F, D>,
				CatchableException<F, A, B>,
				CatchableException<F, A, C>,
				CatchableException<F, A, D>,
				CatchableException<F, A, E>,
				CatchableException<F, B, A>,
				CatchableException<F, B, C>,
				CatchableException<F, B, D>,
				CatchableException<F, B, E>,
				CatchableException<F, C, A>,
				CatchableException<F, C, B>,
				CatchableException<F, C, D>,
				CatchableException<F, C, E>,
				CatchableException<F, D, A>,
				CatchableException<F, D, B>,
				CatchableException<F, D, C>,
				CatchableException<F, D, E>,
				CatchableException<F, E, A>,
				CatchableException<F, E, B>,
				CatchableException<F, E, C>,
				CatchableException<F, E, D>,
				CatchableException<A, B, C, D>,
				CatchableException<A, B, C, E>,
				CatchableException<A, B, C, F>,
				CatchableException<A, B, D, C>,
				CatchableException<A, B, D, E>,
				CatchableException<A, B, D, F>,
				CatchableException<A, B, E, C>,
				CatchableException<A, B, E, D>,
				CatchableException<A, B, E, F>,
				CatchableException<A, B, F, C>,
				CatchableException<A, B, F, D>,
				CatchableException<A, B, F, E>,
				CatchableException<A, C, B, D>,
				CatchableException<A, C, B, E>,
				CatchableException<A, C, B, F>,
				CatchableException<A, C, D, B>,
				CatchableException<A, C, D, E>,
				CatchableException<A, C, D, F>,
				CatchableException<A, C, E, B>,
				CatchableException<A, C, E, D>,
				CatchableException<A, C, E, F>,
				CatchableException<A, C, F, B>,
				CatchableException<A, C, F, D>,
				CatchableException<A, C, F, E>,
				CatchableException<A, D, B, C>,
				CatchableException<A, D, B, E>,
				CatchableException<A, D, B, F>,
				CatchableException<A, D, C, B>,
				CatchableException<A, D, C, E>,
				CatchableException<A, D, C, F>,
				CatchableException<A, D, E, B>,
				CatchableException<A, D, E, C>,
				CatchableException<A, D, E, F>,
				CatchableException<A, D, F, B>,
				CatchableException<A, D, F, C>,
				CatchableException<A, D, F, E>,
				CatchableException<A, E, B, C>,
				CatchableException<A, E, B, D>,
				CatchableException<A, E, B, F>,
				CatchableException<A, E, C, B>,
				CatchableException<A, E, C, D>,
				CatchableException<A, E, C, F>,
				CatchableException<A, E, D, B>,
				CatchableException<A, E, D, C>,
				CatchableException<A, E, D, F>,
				CatchableException<A, E, F, B>,
				CatchableException<A, E, F, C>,
				CatchableException<A, E, F, D>,
				CatchableException<A, F, B, C>,
				CatchableException<A, F, B, D>,
				CatchableException<A, F, B, E>,
				CatchableException<A, F, C, B>,
				CatchableException<A, F, C, D>,
				CatchableException<A, F, C, E>,
				CatchableException<A, F, D, B>,
				CatchableException<A, F, D, C>,
				CatchableException<A, F, D, E>,
				CatchableException<A, F, E, B>,
				CatchableException<A, F, E, C>,
				CatchableException<A, F, E, D>,
				CatchableException<B, A, C, D>,
				CatchableException<B, A, C, E>,
				CatchableException<B, A, C, F>,
				CatchableException<B, A, D, C>,
				CatchableException<B, A, D, E>,
				CatchableException<B, A, D, F>,
				CatchableException<B, A, E, C>,
				CatchableException<B, A, E, D>,
				CatchableException<B, A, E, F>,
				CatchableException<B, A, F, C>,
				CatchableException<B, A, F, D>,
				CatchableException<B, A, F, E>,
				CatchableException<B, C, A, D>,
				CatchableException<B, C, A, E>,
				CatchableException<B, C, A, F>,
				CatchableException<B, C, D, A>,
				CatchableException<B, C, D, E>,
				CatchableException<B, C, D, F>,
				CatchableException<B, C, E, A>,
				CatchableException<B, C, E, D>,
				CatchableException<B, C, E, F>,
				CatchableException<B, C, F, A>,
				CatchableException<B, C, F, D>,
				CatchableException<B, C, F, E>,
				CatchableException<B, D, A, C>,
				CatchableException<B, D, A, E>,
				CatchableException<B, D, A, F>,
				CatchableException<B, D, C, A>,
				CatchableException<B, D, C, E>,
				CatchableException<B, D, C, F>,
				CatchableException<B, D, E, A>,
				CatchableException<B, D, E, C>,
				CatchableException<B, D, E, F>,
				CatchableException<B, D, F, A>,
				CatchableException<B, D, F, C>,
				CatchableException<B, D, F, E>,
				CatchableException<B, E, A, C>,
				CatchableException<B, E, A, D>,
				CatchableException<B, E, A, F>,
				CatchableException<B, E, C, A>,
				CatchableException<B, E, C, D>,
				CatchableException<B, E, C, F>,
				CatchableException<B, E, D, A>,
				CatchableException<B, E, D, C>,
				CatchableException<B, E, D, F>,
				CatchableException<B, E, F, A>,
				CatchableException<B, E, F, C>,
				CatchableException<B, E, F, D>,
				CatchableException<B, F, A, C>,
				CatchableException<B, F, A, D>,
				CatchableException<B, F, A, E>,
				CatchableException<B, F, C, A>,
				CatchableException<B, F, C, D>,
				CatchableException<B, F, C, E>,
				CatchableException<B, F, D, A>,
				CatchableException<B, F, D, C>,
				CatchableException<B, F, D, E>,
				CatchableException<B, F, E, A>,
				CatchableException<B, F, E, C>,
				CatchableException<B, F, E, D>,
				CatchableException<C, A, B, D>,
				CatchableException<C, A, B, E>,
				CatchableException<C, A, B, F>,
				CatchableException<C, A, D, B>,
				CatchableException<C, A, D, E>,
				CatchableException<C, A, D, F>,
				CatchableException<C, A, E, B>,
				CatchableException<C, A, E, D>,
				CatchableException<C, A, E, F>,
				CatchableException<C, A, F, B>,
				CatchableException<C, A, F, D>,
				CatchableException<C, A, F, E>,
				CatchableException<C, B, A, D>,
				CatchableException<C, B, A, E>,
				CatchableException<C, B, A, F>,
				CatchableException<C, B, D, A>,
				CatchableException<C, B, D, E>,
				CatchableException<C, B, D, F>,
				CatchableException<C, B, E, A>,
				CatchableException<C, B, E, D>,
				CatchableException<C, B, E, F>,
				CatchableException<C, B, F, A>,
				CatchableException<C, B, F, D>,
				CatchableException<C, B, F, E>,
				CatchableException<C, D, A, B>,
				CatchableException<C, D, A, E>,
				CatchableException<C, D, A, F>,
				CatchableException<C, D, B, A>,
				CatchableException<C, D, B, E>,
				CatchableException<C, D, B, F>,
				CatchableException<C, D, E, A>,
				CatchableException<C, D, E, B>,
				CatchableException<C, D, E, F>,
				CatchableException<C, D, F, A>,
				CatchableException<C, D, F, B>,
				CatchableException<C, D, F, E>,
				CatchableException<C, E, A, B>,
				CatchableException<C, E, A, D>,
				CatchableException<C, E, A, F>,
				CatchableException<C, E, B, A>,
				CatchableException<C, E, B, D>,
				CatchableException<C, E, B, F>,
				CatchableException<C, E, D, A>,
				CatchableException<C, E, D, B>,
				CatchableException<C, E, D, F>,
				CatchableException<C, E, F, A>,
				CatchableException<C, E, F, B>,
				CatchableException<C, E, F, D>,
				CatchableException<C, F, A, B>,
				CatchableException<C, F, A, D>,
				CatchableException<C, F, A, E>,
				CatchableException<C, F, B, A>,
				CatchableException<C, F, B, D>,
				CatchableException<C, F, B, E>,
				CatchableException<C, F, D, A>,
				CatchableException<C, F, D, B>,
				CatchableException<C, F, D, E>,
				CatchableException<C, F, E, A>,
				CatchableException<C, F, E, B>,
				CatchableException<C, F, E, D>,
				CatchableException<D, A, B, C>,
				CatchableException<D, A, B, E>,
				CatchableException<D, A, B, F>,
				CatchableException<D, A, C, B>,
				CatchableException<D, A, C, E>,
				CatchableException<D, A, C, F>,
				CatchableException<D, A, E, B>,
				CatchableException<D, A, E, C>,
				CatchableException<D, A, E, F>,
				CatchableException<D, A, F, B>,
				CatchableException<D, A, F, C>,
				CatchableException<D, A, F, E>,
				CatchableException<D, B, A, C>,
				CatchableException<D, B, A, E>,
				CatchableException<D, B, A, F>,
				CatchableException<D, B, C, A>,
				CatchableException<D, B, C, E>,
				CatchableException<D, B, C, F>,
				CatchableException<D, B, E, A>,
				CatchableException<D, B, E, C>,
				CatchableException<D, B, E, F>,
				CatchableException<D, B, F, A>,
				CatchableException<D, B, F, C>,
				CatchableException<D, B, F, E>,
				CatchableException<D, C, A, B>,
				CatchableException<D, C, A, E>,
				CatchableException<D, C, A, F>,
				CatchableException<D, C, B, A>,
				CatchableException<D, C, B, E>,
				CatchableException<D, C, B, F>,
				CatchableException<D, C, E, A>,
				CatchableException<D, C, E, B>,
				CatchableException<D, C, E, F>,
				CatchableException<D, C, F, A>,
				CatchableException<D, C, F, B>,
				CatchableException<D, C, F, E>,
				CatchableException<D, E, A, B>,
				CatchableException<D, E, A, C>,
				CatchableException<D, E, A, F>,
				CatchableException<D, E, B, A>,
				CatchableException<D, E, B, C>,
				CatchableException<D, E, B, F>,
				CatchableException<D, E, C, A>,
				CatchableException<D, E, C, B>,
				CatchableException<D, E, C, F>,
				CatchableException<D, E, F, A>,
				CatchableException<D, E, F, B>,
				CatchableException<D, E, F, C>,
				CatchableException<D, F, A, B>,
				CatchableException<D, F, A, C>,
				CatchableException<D, F, A, E>,
				CatchableException<D, F, B, A>,
				CatchableException<D, F, B, C>,
				CatchableException<D, F, B, E>,
				CatchableException<D, F, C, A>,
				CatchableException<D, F, C, B>,
				CatchableException<D, F, C, E>,
				CatchableException<D, F, E, A>,
				CatchableException<D, F, E, B>,
				CatchableException<D, F, E, C>,
				CatchableException<E, A, B, C>,
				CatchableException<E, A, B, D>,
				CatchableException<E, A, B, F>,
				CatchableException<E, A, C, B>,
				CatchableException<E, A, C, D>,
				CatchableException<E, A, C, F>,
				CatchableException<E, A, D, B>,
				CatchableException<E, A, D, C>,
				CatchableException<E, A, D, F>,
				CatchableException<E, A, F, B>,
				CatchableException<E, A, F, C>,
				CatchableException<E, A, F, D>,
				CatchableException<E, B, A, C>,
				CatchableException<E, B, A, D>,
				CatchableException<E, B, A, F>,
				CatchableException<E, B, C, A>,
				CatchableException<E, B, C, D>,
				CatchableException<E, B, C, F>,
				CatchableException<E, B, D, A>,
				CatchableException<E, B, D, C>,
				CatchableException<E, B, D, F>,
				CatchableException<E, B, F, A>,
				CatchableException<E, B, F, C>,
				CatchableException<E, B, F, D>,
				CatchableException<E, C, A, B>,
				CatchableException<E, C, A, D>,
				CatchableException<E, C, A, F>,
				CatchableException<E, C, B, A>,
				CatchableException<E, C, B, D>,
				CatchableException<E, C, B, F>,
				CatchableException<E, C, D, A>,
				CatchableException<E, C, D, B>,
				CatchableException<E, C, D, F>,
				CatchableException<E, C, F, A>,
				CatchableException<E, C, F, B>,
				CatchableException<E, C, F, D>,
				CatchableException<E, D, A, B>,
				CatchableException<E, D, A, C>,
				CatchableException<E, D, A, F>,
				CatchableException<E, D, B, A>,
				CatchableException<E, D, B, C>,
				CatchableException<E, D, B, F>,
				CatchableException<E, D, C, A>,
				CatchableException<E, D, C, B>,
				CatchableException<E, D, C, F>,
				CatchableException<E, D, F, A>,
				CatchableException<E, D, F, B>,
				CatchableException<E, D, F, C>,
				CatchableException<E, F, A, B>,
				CatchableException<E, F, A, C>,
				CatchableException<E, F, A, D>,
				CatchableException<E, F, B, A>,
				CatchableException<E, F, B, C>,
				CatchableException<E, F, B, D>,
				CatchableException<E, F, C, A>,
				CatchableException<E, F, C, B>,
				CatchableException<E, F, C, D>,
				CatchableException<E, F, D, A>,
				CatchableException<E, F, D, B>,
				CatchableException<E, F, D, C>,
				CatchableException<F, A, B, C>,
				CatchableException<F, A, B, D>,
				CatchableException<F, A, B, E>,
				CatchableException<F, A, C, B>,
				CatchableException<F, A, C, D>,
				CatchableException<F, A, C, E>,
				CatchableException<F, A, D, B>,
				CatchableException<F, A, D, C>,
				CatchableException<F, A, D, E>,
				CatchableException<F, A, E, B>,
				CatchableException<F, A, E, C>,
				CatchableException<F, A, E, D>,
				CatchableException<F, B, A, C>,
				CatchableException<F, B, A, D>,
				CatchableException<F, B, A, E>,
				CatchableException<F, B, C, A>,
				CatchableException<F, B, C, D>,
				CatchableException<F, B, C, E>,
				CatchableException<F, B, D, A>,
				CatchableException<F, B, D, C>,
				CatchableException<F, B, D, E>,
				CatchableException<F, B, E, A>,
				CatchableException<F, B, E, C>,
				CatchableException<F, B, E, D>,
				CatchableException<F, C, A, B>,
				CatchableException<F, C, A, D>,
				CatchableException<F, C, A, E>,
				CatchableException<F, C, B, A>,
				CatchableException<F, C, B, D>,
				CatchableException<F, C, B, E>,
				CatchableException<F, C, D, A>,
				CatchableException<F, C, D, B>,
				CatchableException<F, C, D, E>,
				CatchableException<F, C, E, A>,
				CatchableException<F, C, E, B>,
				CatchableException<F, C, E, D>,
				CatchableException<F, D, A, B>,
				CatchableException<F, D, A, C>,
				CatchableException<F, D, A, E>,
				CatchableException<F, D, B, A>,
				CatchableException<F, D, B, C>,
				CatchableException<F, D, B, E>,
				CatchableException<F, D, C, A>,
				CatchableException<F, D, C, B>,
				CatchableException<F, D, C, E>,
				CatchableException<F, D, E, A>,
				CatchableException<F, D, E, B>,
				CatchableException<F, D, E, C>,
				CatchableException<F, E, A, B>,
				CatchableException<F, E, A, C>,
				CatchableException<F, E, A, D>,
				CatchableException<F, E, B, A>,
				CatchableException<F, E, B, C>,
				CatchableException<F, E, B, D>,
				CatchableException<F, E, C, A>,
				CatchableException<F, E, C, B>,
				CatchableException<F, E, C, D>,
				CatchableException<F, E, D, A>,
				CatchableException<F, E, D, B>,
				CatchableException<F, E, D, C>,
				CatchableException<A, B, C, D, E>,
				CatchableException<A, B, C, D, F>,
				CatchableException<A, B, C, E, D>,
				CatchableException<A, B, C, E, F>,
				CatchableException<A, B, C, F, D>,
				CatchableException<A, B, C, F, E>,
				CatchableException<A, B, D, C, E>,
				CatchableException<A, B, D, C, F>,
				CatchableException<A, B, D, E, C>,
				CatchableException<A, B, D, E, F>,
				CatchableException<A, B, D, F, C>,
				CatchableException<A, B, D, F, E>,
				CatchableException<A, B, E, C, D>,
				CatchableException<A, B, E, C, F>,
				CatchableException<A, B, E, D, C>,
				CatchableException<A, B, E, D, F>,
				CatchableException<A, B, E, F, C>,
				CatchableException<A, B, E, F, D>,
				CatchableException<A, B, F, C, D>,
				CatchableException<A, B, F, C, E>,
				CatchableException<A, B, F, D, C>,
				CatchableException<A, B, F, D, E>,
				CatchableException<A, B, F, E, C>,
				CatchableException<A, B, F, E, D>,
				CatchableException<A, C, B, D, E>,
				CatchableException<A, C, B, D, F>,
				CatchableException<A, C, B, E, D>,
				CatchableException<A, C, B, E, F>,
				CatchableException<A, C, B, F, D>,
				CatchableException<A, C, B, F, E>,
				CatchableException<A, C, D, B, E>,
				CatchableException<A, C, D, B, F>,
				CatchableException<A, C, D, E, B>,
				CatchableException<A, C, D, E, F>,
				CatchableException<A, C, D, F, B>,
				CatchableException<A, C, D, F, E>,
				CatchableException<A, C, E, B, D>,
				CatchableException<A, C, E, B, F>,
				CatchableException<A, C, E, D, B>,
				CatchableException<A, C, E, D, F>,
				CatchableException<A, C, E, F, B>,
				CatchableException<A, C, E, F, D>,
				CatchableException<A, C, F, B, D>,
				CatchableException<A, C, F, B, E>,
				CatchableException<A, C, F, D, B>,
				CatchableException<A, C, F, D, E>,
				CatchableException<A, C, F, E, B>,
				CatchableException<A, C, F, E, D>,
				CatchableException<A, D, B, C, E>,
				CatchableException<A, D, B, C, F>,
				CatchableException<A, D, B, E, C>,
				CatchableException<A, D, B, E, F>,
				CatchableException<A, D, B, F, C>,
				CatchableException<A, D, B, F, E>,
				CatchableException<A, D, C, B, E>,
				CatchableException<A, D, C, B, F>,
				CatchableException<A, D, C, E, B>,
				CatchableException<A, D, C, E, F>,
				CatchableException<A, D, C, F, B>,
				CatchableException<A, D, C, F, E>,
				CatchableException<A, D, E, B, C>,
				CatchableException<A, D, E, B, F>,
				CatchableException<A, D, E, C, B>,
				CatchableException<A, D, E, C, F>,
				CatchableException<A, D, E, F, B>,
				CatchableException<A, D, E, F, C>,
				CatchableException<A, D, F, B, C>,
				CatchableException<A, D, F, B, E>,
				CatchableException<A, D, F, C, B>,
				CatchableException<A, D, F, C, E>,
				CatchableException<A, D, F, E, B>,
				CatchableException<A, D, F, E, C>,
				CatchableException<A, E, B, C, D>,
				CatchableException<A, E, B, C, F>,
				CatchableException<A, E, B, D, C>,
				CatchableException<A, E, B, D, F>,
				CatchableException<A, E, B, F, C>,
				CatchableException<A, E, B, F, D>,
				CatchableException<A, E, C, B, D>,
				CatchableException<A, E, C, B, F>,
				CatchableException<A, E, C, D, B>,
				CatchableException<A, E, C, D, F>,
				CatchableException<A, E, C, F, B>,
				CatchableException<A, E, C, F, D>,
				CatchableException<A, E, D, B, C>,
				CatchableException<A, E, D, B, F>,
				CatchableException<A, E, D, C, B>,
				CatchableException<A, E, D, C, F>,
				CatchableException<A, E, D, F, B>,
				CatchableException<A, E, D, F, C>,
				CatchableException<A, E, F, B, C>,
				CatchableException<A, E, F, B, D>,
				CatchableException<A, E, F, C, B>,
				CatchableException<A, E, F, C, D>,
				CatchableException<A, E, F, D, B>,
				CatchableException<A, E, F, D, C>,
				CatchableException<A, F, B, C, D>,
				CatchableException<A, F, B, C, E>,
				CatchableException<A, F, B, D, C>,
				CatchableException<A, F, B, D, E>,
				CatchableException<A, F, B, E, C>,
				CatchableException<A, F, B, E, D>,
				CatchableException<A, F, C, B, D>,
				CatchableException<A, F, C, B, E>,
				CatchableException<A, F, C, D, B>,
				CatchableException<A, F, C, D, E>,
				CatchableException<A, F, C, E, B>,
				CatchableException<A, F, C, E, D>,
				CatchableException<A, F, D, B, C>,
				CatchableException<A, F, D, B, E>,
				CatchableException<A, F, D, C, B>,
				CatchableException<A, F, D, C, E>,
				CatchableException<A, F, D, E, B>,
				CatchableException<A, F, D, E, C>,
				CatchableException<A, F, E, B, C>,
				CatchableException<A, F, E, B, D>,
				CatchableException<A, F, E, C, B>,
				CatchableException<A, F, E, C, D>,
				CatchableException<A, F, E, D, B>,
				CatchableException<A, F, E, D, C>,
				CatchableException<B, A, C, D, E>,
				CatchableException<B, A, C, D, F>,
				CatchableException<B, A, C, E, D>,
				CatchableException<B, A, C, E, F>,
				CatchableException<B, A, C, F, D>,
				CatchableException<B, A, C, F, E>,
				CatchableException<B, A, D, C, E>,
				CatchableException<B, A, D, C, F>,
				CatchableException<B, A, D, E, C>,
				CatchableException<B, A, D, E, F>,
				CatchableException<B, A, D, F, C>,
				CatchableException<B, A, D, F, E>,
				CatchableException<B, A, E, C, D>,
				CatchableException<B, A, E, C, F>,
				CatchableException<B, A, E, D, C>,
				CatchableException<B, A, E, D, F>,
				CatchableException<B, A, E, F, C>,
				CatchableException<B, A, E, F, D>,
				CatchableException<B, A, F, C, D>,
				CatchableException<B, A, F, C, E>,
				CatchableException<B, A, F, D, C>,
				CatchableException<B, A, F, D, E>,
				CatchableException<B, A, F, E, C>,
				CatchableException<B, A, F, E, D>,
				CatchableException<B, C, A, D, E>,
				CatchableException<B, C, A, D, F>,
				CatchableException<B, C, A, E, D>,
				CatchableException<B, C, A, E, F>,
				CatchableException<B, C, A, F, D>,
				CatchableException<B, C, A, F, E>,
				CatchableException<B, C, D, A, E>,
				CatchableException<B, C, D, A, F>,
				CatchableException<B, C, D, E, A>,
				CatchableException<B, C, D, E, F>,
				CatchableException<B, C, D, F, A>,
				CatchableException<B, C, D, F, E>,
				CatchableException<B, C, E, A, D>,
				CatchableException<B, C, E, A, F>,
				CatchableException<B, C, E, D, A>,
				CatchableException<B, C, E, D, F>,
				CatchableException<B, C, E, F, A>,
				CatchableException<B, C, E, F, D>,
				CatchableException<B, C, F, A, D>,
				CatchableException<B, C, F, A, E>,
				CatchableException<B, C, F, D, A>,
				CatchableException<B, C, F, D, E>,
				CatchableException<B, C, F, E, A>,
				CatchableException<B, C, F, E, D>,
				CatchableException<B, D, A, C, E>,
				CatchableException<B, D, A, C, F>,
				CatchableException<B, D, A, E, C>,
				CatchableException<B, D, A, E, F>,
				CatchableException<B, D, A, F, C>,
				CatchableException<B, D, A, F, E>,
				CatchableException<B, D, C, A, E>,
				CatchableException<B, D, C, A, F>,
				CatchableException<B, D, C, E, A>,
				CatchableException<B, D, C, E, F>,
				CatchableException<B, D, C, F, A>,
				CatchableException<B, D, C, F, E>,
				CatchableException<B, D, E, A, C>,
				CatchableException<B, D, E, A, F>,
				CatchableException<B, D, E, C, A>,
				CatchableException<B, D, E, C, F>,
				CatchableException<B, D, E, F, A>,
				CatchableException<B, D, E, F, C>,
				CatchableException<B, D, F, A, C>,
				CatchableException<B, D, F, A, E>,
				CatchableException<B, D, F, C, A>,
				CatchableException<B, D, F, C, E>,
				CatchableException<B, D, F, E, A>,
				CatchableException<B, D, F, E, C>,
				CatchableException<B, E, A, C, D>,
				CatchableException<B, E, A, C, F>,
				CatchableException<B, E, A, D, C>,
				CatchableException<B, E, A, D, F>,
				CatchableException<B, E, A, F, C>,
				CatchableException<B, E, A, F, D>,
				CatchableException<B, E, C, A, D>,
				CatchableException<B, E, C, A, F>,
				CatchableException<B, E, C, D, A>,
				CatchableException<B, E, C, D, F>,
				CatchableException<B, E, C, F, A>,
				CatchableException<B, E, C, F, D>,
				CatchableException<B, E, D, A, C>,
				CatchableException<B, E, D, A, F>,
				CatchableException<B, E, D, C, A>,
				CatchableException<B, E, D, C, F>,
				CatchableException<B, E, D, F, A>,
				CatchableException<B, E, D, F, C>,
				CatchableException<B, E, F, A, C>,
				CatchableException<B, E, F, A, D>,
				CatchableException<B, E, F, C, A>,
				CatchableException<B, E, F, C, D>,
				CatchableException<B, E, F, D, A>,
				CatchableException<B, E, F, D, C>,
				CatchableException<B, F, A, C, D>,
				CatchableException<B, F, A, C, E>,
				CatchableException<B, F, A, D, C>,
				CatchableException<B, F, A, D, E>,
				CatchableException<B, F, A, E, C>,
				CatchableException<B, F, A, E, D>,
				CatchableException<B, F, C, A, D>,
				CatchableException<B, F, C, A, E>,
				CatchableException<B, F, C, D, A>,
				CatchableException<B, F, C, D, E>,
				CatchableException<B, F, C, E, A>,
				CatchableException<B, F, C, E, D>,
				CatchableException<B, F, D, A, C>,
				CatchableException<B, F, D, A, E>,
				CatchableException<B, F, D, C, A>,
				CatchableException<B, F, D, C, E>,
				CatchableException<B, F, D, E, A>,
				CatchableException<B, F, D, E, C>,
				CatchableException<B, F, E, A, C>,
				CatchableException<B, F, E, A, D>,
				CatchableException<B, F, E, C, A>,
				CatchableException<B, F, E, C, D>,
				CatchableException<B, F, E, D, A>,
				CatchableException<B, F, E, D, C>,
				CatchableException<C, A, B, D, E>,
				CatchableException<C, A, B, D, F>,
				CatchableException<C, A, B, E, D>,
				CatchableException<C, A, B, E, F>,
				CatchableException<C, A, B, F, D>,
				CatchableException<C, A, B, F, E>,
				CatchableException<C, A, D, B, E>,
				CatchableException<C, A, D, B, F>,
				CatchableException<C, A, D, E, B>,
				CatchableException<C, A, D, E, F>,
				CatchableException<C, A, D, F, B>,
				CatchableException<C, A, D, F, E>,
				CatchableException<C, A, E, B, D>,
				CatchableException<C, A, E, B, F>,
				CatchableException<C, A, E, D, B>,
				CatchableException<C, A, E, D, F>,
				CatchableException<C, A, E, F, B>,
				CatchableException<C, A, E, F, D>,
				CatchableException<C, A, F, B, D>,
				CatchableException<C, A, F, B, E>,
				CatchableException<C, A, F, D, B>,
				CatchableException<C, A, F, D, E>,
				CatchableException<C, A, F, E, B>,
				CatchableException<C, A, F, E, D>,
				CatchableException<C, B, A, D, E>,
				CatchableException<C, B, A, D, F>,
				CatchableException<C, B, A, E, D>,
				CatchableException<C, B, A, E, F>,
				CatchableException<C, B, A, F, D>,
				CatchableException<C, B, A, F, E>,
				CatchableException<C, B, D, A, E>,
				CatchableException<C, B, D, A, F>,
				CatchableException<C, B, D, E, A>,
				CatchableException<C, B, D, E, F>,
				CatchableException<C, B, D, F, A>,
				CatchableException<C, B, D, F, E>,
				CatchableException<C, B, E, A, D>,
				CatchableException<C, B, E, A, F>,
				CatchableException<C, B, E, D, A>,
				CatchableException<C, B, E, D, F>,
				CatchableException<C, B, E, F, A>,
				CatchableException<C, B, E, F, D>,
				CatchableException<C, B, F, A, D>,
				CatchableException<C, B, F, A, E>,
				CatchableException<C, B, F, D, A>,
				CatchableException<C, B, F, D, E>,
				CatchableException<C, B, F, E, A>,
				CatchableException<C, B, F, E, D>,
				CatchableException<C, D, A, B, E>,
				CatchableException<C, D, A, B, F>,
				CatchableException<C, D, A, E, B>,
				CatchableException<C, D, A, E, F>,
				CatchableException<C, D, A, F, B>,
				CatchableException<C, D, A, F, E>,
				CatchableException<C, D, B, A, E>,
				CatchableException<C, D, B, A, F>,
				CatchableException<C, D, B, E, A>,
				CatchableException<C, D, B, E, F>,
				CatchableException<C, D, B, F, A>,
				CatchableException<C, D, B, F, E>,
				CatchableException<C, D, E, A, B>,
				CatchableException<C, D, E, A, F>,
				CatchableException<C, D, E, B, A>,
				CatchableException<C, D, E, B, F>,
				CatchableException<C, D, E, F, A>,
				CatchableException<C, D, E, F, B>,
				CatchableException<C, D, F, A, B>,
				CatchableException<C, D, F, A, E>,
				CatchableException<C, D, F, B, A>,
				CatchableException<C, D, F, B, E>,
				CatchableException<C, D, F, E, A>,
				CatchableException<C, D, F, E, B>,
				CatchableException<C, E, A, B, D>,
				CatchableException<C, E, A, B, F>,
				CatchableException<C, E, A, D, B>,
				CatchableException<C, E, A, D, F>,
				CatchableException<C, E, A, F, B>,
				CatchableException<C, E, A, F, D>,
				CatchableException<C, E, B, A, D>,
				CatchableException<C, E, B, A, F>,
				CatchableException<C, E, B, D, A>,
				CatchableException<C, E, B, D, F>,
				CatchableException<C, E, B, F, A>,
				CatchableException<C, E, B, F, D>,
				CatchableException<C, E, D, A, B>,
				CatchableException<C, E, D, A, F>,
				CatchableException<C, E, D, B, A>,
				CatchableException<C, E, D, B, F>,
				CatchableException<C, E, D, F, A>,
				CatchableException<C, E, D, F, B>,
				CatchableException<C, E, F, A, B>,
				CatchableException<C, E, F, A, D>,
				CatchableException<C, E, F, B, A>,
				CatchableException<C, E, F, B, D>,
				CatchableException<C, E, F, D, A>,
				CatchableException<C, E, F, D, B>,
				CatchableException<C, F, A, B, D>,
				CatchableException<C, F, A, B, E>,
				CatchableException<C, F, A, D, B>,
				CatchableException<C, F, A, D, E>,
				CatchableException<C, F, A, E, B>,
				CatchableException<C, F, A, E, D>,
				CatchableException<C, F, B, A, D>,
				CatchableException<C, F, B, A, E>,
				CatchableException<C, F, B, D, A>,
				CatchableException<C, F, B, D, E>,
				CatchableException<C, F, B, E, A>,
				CatchableException<C, F, B, E, D>,
				CatchableException<C, F, D, A, B>,
				CatchableException<C, F, D, A, E>,
				CatchableException<C, F, D, B, A>,
				CatchableException<C, F, D, B, E>,
				CatchableException<C, F, D, E, A>,
				CatchableException<C, F, D, E, B>,
				CatchableException<C, F, E, A, B>,
				CatchableException<C, F, E, A, D>,
				CatchableException<C, F, E, B, A>,
				CatchableException<C, F, E, B, D>,
				CatchableException<C, F, E, D, A>,
				CatchableException<C, F, E, D, B>,
				CatchableException<D, A, B, C, E>,
				CatchableException<D, A, B, C, F>,
				CatchableException<D, A, B, E, C>,
				CatchableException<D, A, B, E, F>,
				CatchableException<D, A, B, F, C>,
				CatchableException<D, A, B, F, E>,
				CatchableException<D, A, C, B, E>,
				CatchableException<D, A, C, B, F>,
				CatchableException<D, A, C, E, B>,
				CatchableException<D, A, C, E, F>,
				CatchableException<D, A, C, F, B>,
				CatchableException<D, A, C, F, E>,
				CatchableException<D, A, E, B, C>,
				CatchableException<D, A, E, B, F>,
				CatchableException<D, A, E, C, B>,
				CatchableException<D, A, E, C, F>,
				CatchableException<D, A, E, F, B>,
				CatchableException<D, A, E, F, C>,
				CatchableException<D, A, F, B, C>,
				CatchableException<D, A, F, B, E>,
				CatchableException<D, A, F, C, B>,
				CatchableException<D, A, F, C, E>,
				CatchableException<D, A, F, E, B>,
				CatchableException<D, A, F, E, C>,
				CatchableException<D, B, A, C, E>,
				CatchableException<D, B, A, C, F>,
				CatchableException<D, B, A, E, C>,
				CatchableException<D, B, A, E, F>,
				CatchableException<D, B, A, F, C>,
				CatchableException<D, B, A, F, E>,
				CatchableException<D, B, C, A, E>,
				CatchableException<D, B, C, A, F>,
				CatchableException<D, B, C, E, A>,
				CatchableException<D, B, C, E, F>,
				CatchableException<D, B, C, F, A>,
				CatchableException<D, B, C, F, E>,
				CatchableException<D, B, E, A, C>,
				CatchableException<D, B, E, A, F>,
				CatchableException<D, B, E, C, A>,
				CatchableException<D, B, E, C, F>,
				CatchableException<D, B, E, F, A>,
				CatchableException<D, B, E, F, C>,
				CatchableException<D, B, F, A, C>,
				CatchableException<D, B, F, A, E>,
				CatchableException<D, B, F, C, A>,
				CatchableException<D, B, F, C, E>,
				CatchableException<D, B, F, E, A>,
				CatchableException<D, B, F, E, C>,
				CatchableException<D, C, A, B, E>,
				CatchableException<D, C, A, B, F>,
				CatchableException<D, C, A, E, B>,
				CatchableException<D, C, A, E, F>,
				CatchableException<D, C, A, F, B>,
				CatchableException<D, C, A, F, E>,
				CatchableException<D, C, B, A, E>,
				CatchableException<D, C, B, A, F>,
				CatchableException<D, C, B, E, A>,
				CatchableException<D, C, B, E, F>,
				CatchableException<D, C, B, F, A>,
				CatchableException<D, C, B, F, E>,
				CatchableException<D, C, E, A, B>,
				CatchableException<D, C, E, A, F>,
				CatchableException<D, C, E, B, A>,
				CatchableException<D, C, E, B, F>,
				CatchableException<D, C, E, F, A>,
				CatchableException<D, C, E, F, B>,
				CatchableException<D, C, F, A, B>,
				CatchableException<D, C, F, A, E>,
				CatchableException<D, C, F, B, A>,
				CatchableException<D, C, F, B, E>,
				CatchableException<D, C, F, E, A>,
				CatchableException<D, C, F, E, B>,
				CatchableException<D, E, A, B, C>,
				CatchableException<D, E, A, B, F>,
				CatchableException<D, E, A, C, B>,
				CatchableException<D, E, A, C, F>,
				CatchableException<D, E, A, F, B>,
				CatchableException<D, E, A, F, C>,
				CatchableException<D, E, B, A, C>,
				CatchableException<D, E, B, A, F>,
				CatchableException<D, E, B, C, A>,
				CatchableException<D, E, B, C, F>,
				CatchableException<D, E, B, F, A>,
				CatchableException<D, E, B, F, C>,
				CatchableException<D, E, C, A, B>,
				CatchableException<D, E, C, A, F>,
				CatchableException<D, E, C, B, A>,
				CatchableException<D, E, C, B, F>,
				CatchableException<D, E, C, F, A>,
				CatchableException<D, E, C, F, B>,
				CatchableException<D, E, F, A, B>,
				CatchableException<D, E, F, A, C>,
				CatchableException<D, E, F, B, A>,
				CatchableException<D, E, F, B, C>,
				CatchableException<D, E, F, C, A>,
				CatchableException<D, E, F, C, B>,
				CatchableException<D, F, A, B, C>,
				CatchableException<D, F, A, B, E>,
				CatchableException<D, F, A, C, B>,
				CatchableException<D, F, A, C, E>,
				CatchableException<D, F, A, E, B>,
				CatchableException<D, F, A, E, C>,
				CatchableException<D, F, B, A, C>,
				CatchableException<D, F, B, A, E>,
				CatchableException<D, F, B, C, A>,
				CatchableException<D, F, B, C, E>,
				CatchableException<D, F, B, E, A>,
				CatchableException<D, F, B, E, C>,
				CatchableException<D, F, C, A, B>,
				CatchableException<D, F, C, A, E>,
				CatchableException<D, F, C, B, A>,
				CatchableException<D, F, C, B, E>,
				CatchableException<D, F, C, E, A>,
				CatchableException<D, F, C, E, B>,
				CatchableException<D, F, E, A, B>,
				CatchableException<D, F, E, A, C>,
				CatchableException<D, F, E, B, A>,
				CatchableException<D, F, E, B, C>,
				CatchableException<D, F, E, C, A>,
				CatchableException<D, F, E, C, B>,
				CatchableException<E, A, B, C, D>,
				CatchableException<E, A, B, C, F>,
				CatchableException<E, A, B, D, C>,
				CatchableException<E, A, B, D, F>,
				CatchableException<E, A, B, F, C>,
				CatchableException<E, A, B, F, D>,
				CatchableException<E, A, C, B, D>,
				CatchableException<E, A, C, B, F>,
				CatchableException<E, A, C, D, B>,
				CatchableException<E, A, C, D, F>,
				CatchableException<E, A, C, F, B>,
				CatchableException<E, A, C, F, D>,
				CatchableException<E, A, D, B, C>,
				CatchableException<E, A, D, B, F>,
				CatchableException<E, A, D, C, B>,
				CatchableException<E, A, D, C, F>,
				CatchableException<E, A, D, F, B>,
				CatchableException<E, A, D, F, C>,
				CatchableException<E, A, F, B, C>,
				CatchableException<E, A, F, B, D>,
				CatchableException<E, A, F, C, B>,
				CatchableException<E, A, F, C, D>,
				CatchableException<E, A, F, D, B>,
				CatchableException<E, A, F, D, C>,
				CatchableException<E, B, A, C, D>,
				CatchableException<E, B, A, C, F>,
				CatchableException<E, B, A, D, C>,
				CatchableException<E, B, A, D, F>,
				CatchableException<E, B, A, F, C>,
				CatchableException<E, B, A, F, D>,
				CatchableException<E, B, C, A, D>,
				CatchableException<E, B, C, A, F>,
				CatchableException<E, B, C, D, A>,
				CatchableException<E, B, C, D, F>,
				CatchableException<E, B, C, F, A>,
				CatchableException<E, B, C, F, D>,
				CatchableException<E, B, D, A, C>,
				CatchableException<E, B, D, A, F>,
				CatchableException<E, B, D, C, A>,
				CatchableException<E, B, D, C, F>,
				CatchableException<E, B, D, F, A>,
				CatchableException<E, B, D, F, C>,
				CatchableException<E, B, F, A, C>,
				CatchableException<E, B, F, A, D>,
				CatchableException<E, B, F, C, A>,
				CatchableException<E, B, F, C, D>,
				CatchableException<E, B, F, D, A>,
				CatchableException<E, B, F, D, C>,
				CatchableException<E, C, A, B, D>,
				CatchableException<E, C, A, B, F>,
				CatchableException<E, C, A, D, B>,
				CatchableException<E, C, A, D, F>,
				CatchableException<E, C, A, F, B>,
				CatchableException<E, C, A, F, D>,
				CatchableException<E, C, B, A, D>,
				CatchableException<E, C, B, A, F>,
				CatchableException<E, C, B, D, A>,
				CatchableException<E, C, B, D, F>,
				CatchableException<E, C, B, F, A>,
				CatchableException<E, C, B, F, D>,
				CatchableException<E, C, D, A, B>,
				CatchableException<E, C, D, A, F>,
				CatchableException<E, C, D, B, A>,
				CatchableException<E, C, D, B, F>,
				CatchableException<E, C, D, F, A>,
				CatchableException<E, C, D, F, B>,
				CatchableException<E, C, F, A, B>,
				CatchableException<E, C, F, A, D>,
				CatchableException<E, C, F, B, A>,
				CatchableException<E, C, F, B, D>,
				CatchableException<E, C, F, D, A>,
				CatchableException<E, C, F, D, B>,
				CatchableException<E, D, A, B, C>,
				CatchableException<E, D, A, B, F>,
				CatchableException<E, D, A, C, B>,
				CatchableException<E, D, A, C, F>,
				CatchableException<E, D, A, F, B>,
				CatchableException<E, D, A, F, C>,
				CatchableException<E, D, B, A, C>,
				CatchableException<E, D, B, A, F>,
				CatchableException<E, D, B, C, A>,
				CatchableException<E, D, B, C, F>,
				CatchableException<E, D, B, F, A>,
				CatchableException<E, D, B, F, C>,
				CatchableException<E, D, C, A, B>,
				CatchableException<E, D, C, A, F>,
				CatchableException<E, D, C, B, A>,
				CatchableException<E, D, C, B, F>,
				CatchableException<E, D, C, F, A>,
				CatchableException<E, D, C, F, B>,
				CatchableException<E, D, F, A, B>,
				CatchableException<E, D, F, A, C>,
				CatchableException<E, D, F, B, A>,
				CatchableException<E, D, F, B, C>,
				CatchableException<E, D, F, C, A>,
				CatchableException<E, D, F, C, B>,
				CatchableException<E, F, A, B, C>,
				CatchableException<E, F, A, B, D>,
				CatchableException<E, F, A, C, B>,
				CatchableException<E, F, A, C, D>,
				CatchableException<E, F, A, D, B>,
				CatchableException<E, F, A, D, C>,
				CatchableException<E, F, B, A, C>,
				CatchableException<E, F, B, A, D>,
				CatchableException<E, F, B, C, A>,
				CatchableException<E, F, B, C, D>,
				CatchableException<E, F, B, D, A>,
				CatchableException<E, F, B, D, C>,
				CatchableException<E, F, C, A, B>,
				CatchableException<E, F, C, A, D>,
				CatchableException<E, F, C, B, A>,
				CatchableException<E, F, C, B, D>,
				CatchableException<E, F, C, D, A>,
				CatchableException<E, F, C, D, B>,
				CatchableException<E, F, D, A, B>,
				CatchableException<E, F, D, A, C>,
				CatchableException<E, F, D, B, A>,
				CatchableException<E, F, D, B, C>,
				CatchableException<E, F, D, C, A>,
				CatchableException<E, F, D, C, B>,
				CatchableException<F, A, B, C, D>,
				CatchableException<F, A, B, C, E>,
				CatchableException<F, A, B, D, C>,
				CatchableException<F, A, B, D, E>,
				CatchableException<F, A, B, E, C>,
				CatchableException<F, A, B, E, D>,
				CatchableException<F, A, C, B, D>,
				CatchableException<F, A, C, B, E>,
				CatchableException<F, A, C, D, B>,
				CatchableException<F, A, C, D, E>,
				CatchableException<F, A, C, E, B>,
				CatchableException<F, A, C, E, D>,
				CatchableException<F, A, D, B, C>,
				CatchableException<F, A, D, B, E>,
				CatchableException<F, A, D, C, B>,
				CatchableException<F, A, D, C, E>,
				CatchableException<F, A, D, E, B>,
				CatchableException<F, A, D, E, C>,
				CatchableException<F, A, E, B, C>,
				CatchableException<F, A, E, B, D>,
				CatchableException<F, A, E, C, B>,
				CatchableException<F, A, E, C, D>,
				CatchableException<F, A, E, D, B>,
				CatchableException<F, A, E, D, C>,
				CatchableException<F, B, A, C, D>,
				CatchableException<F, B, A, C, E>,
				CatchableException<F, B, A, D, C>,
				CatchableException<F, B, A, D, E>,
				CatchableException<F, B, A, E, C>,
				CatchableException<F, B, A, E, D>,
				CatchableException<F, B, C, A, D>,
				CatchableException<F, B, C, A, E>,
				CatchableException<F, B, C, D, A>,
				CatchableException<F, B, C, D, E>,
				CatchableException<F, B, C, E, A>,
				CatchableException<F, B, C, E, D>,
				CatchableException<F, B, D, A, C>,
				CatchableException<F, B, D, A, E>,
				CatchableException<F, B, D, C, A>,
				CatchableException<F, B, D, C, E>,
				CatchableException<F, B, D, E, A>,
				CatchableException<F, B, D, E, C>,
				CatchableException<F, B, E, A, C>,
				CatchableException<F, B, E, A, D>,
				CatchableException<F, B, E, C, A>,
				CatchableException<F, B, E, C, D>,
				CatchableException<F, B, E, D, A>,
				CatchableException<F, B, E, D, C>,
				CatchableException<F, C, A, B, D>,
				CatchableException<F, C, A, B, E>,
				CatchableException<F, C, A, D, B>,
				CatchableException<F, C, A, D, E>,
				CatchableException<F, C, A, E, B>,
				CatchableException<F, C, A, E, D>,
				CatchableException<F, C, B, A, D>,
				CatchableException<F, C, B, A, E>,
				CatchableException<F, C, B, D, A>,
				CatchableException<F, C, B, D, E>,
				CatchableException<F, C, B, E, A>,
				CatchableException<F, C, B, E, D>,
				CatchableException<F, C, D, A, B>,
				CatchableException<F, C, D, A, E>,
				CatchableException<F, C, D, B, A>,
				CatchableException<F, C, D, B, E>,
				CatchableException<F, C, D, E, A>,
				CatchableException<F, C, D, E, B>,
				CatchableException<F, C, E, A, B>,
				CatchableException<F, C, E, A, D>,
				CatchableException<F, C, E, B, A>,
				CatchableException<F, C, E, B, D>,
				CatchableException<F, C, E, D, A>,
				CatchableException<F, C, E, D, B>,
				CatchableException<F, D, A, B, C>,
				CatchableException<F, D, A, B, E>,
				CatchableException<F, D, A, C, B>,
				CatchableException<F, D, A, C, E>,
				CatchableException<F, D, A, E, B>,
				CatchableException<F, D, A, E, C>,
				CatchableException<F, D, B, A, C>,
				CatchableException<F, D, B, A, E>,
				CatchableException<F, D, B, C, A>,
				CatchableException<F, D, B, C, E>,
				CatchableException<F, D, B, E, A>,
				CatchableException<F, D, B, E, C>,
				CatchableException<F, D, C, A, B>,
				CatchableException<F, D, C, A, E>,
				CatchableException<F, D, C, B, A>,
				CatchableException<F, D, C, B, E>,
				CatchableException<F, D, C, E, A>,
				CatchableException<F, D, C, E, B>,
				CatchableException<F, D, E, A, B>,
				CatchableException<F, D, E, A, C>,
				CatchableException<F, D, E, B, A>,
				CatchableException<F, D, E, B, C>,
				CatchableException<F, D, E, C, A>,
				CatchableException<F, D, E, C, B>,
				CatchableException<F, E, A, B, C>,
				CatchableException<F, E, A, B, D>,
				CatchableException<F, E, A, C, B>,
				CatchableException<F, E, A, C, D>,
				CatchableException<F, E, A, D, B>,
				CatchableException<F, E, A, D, C>,
				CatchableException<F, E, B, A, C>,
				CatchableException<F, E, B, A, D>,
				CatchableException<F, E, B, C, A>,
				CatchableException<F, E, B, C, D>,
				CatchableException<F, E, B, D, A>,
				CatchableException<F, E, B, D, C>,
				CatchableException<F, E, C, A, B>,
				CatchableException<F, E, C, A, D>,
				CatchableException<F, E, C, B, A>,
				CatchableException<F, E, C, B, D>,
				CatchableException<F, E, C, D, A>,
				CatchableException<F, E, C, D, B>,
				CatchableException<F, E, D, A, B>,
				CatchableException<F, E, D, A, C>,
				CatchableException<F, E, D, B, A>,
				CatchableException<F, E, D, B, C>,
				CatchableException<F, E, D, C, A>,
				CatchableException<F, E, D, C, B>,
				CatchableException<A, B, C, D, E, F>,
				CatchableException<A, B, C, D, F, E>,
				CatchableException<A, B, C, E, D, F>,
				CatchableException<A, B, C, E, F, D>,
				CatchableException<A, B, C, F, D, E>,
				CatchableException<A, B, C, F, E, D>,
				CatchableException<A, B, D, C, E, F>,
				CatchableException<A, B, D, C, F, E>,
				CatchableException<A, B, D, E, C, F>,
				CatchableException<A, B, D, E, F, C>,
				CatchableException<A, B, D, F, C, E>,
				CatchableException<A, B, D, F, E, C>,
				CatchableException<A, B, E, C, D, F>,
				CatchableException<A, B, E, C, F, D>,
				CatchableException<A, B, E, D, C, F>,
				CatchableException<A, B, E, D, F, C>,
				CatchableException<A, B, E, F, C, D>,
				CatchableException<A, B, E, F, D, C>,
				CatchableException<A, B, F, C, D, E>,
				CatchableException<A, B, F, C, E, D>,
				CatchableException<A, B, F, D, C, E>,
				CatchableException<A, B, F, D, E, C>,
				CatchableException<A, B, F, E, C, D>,
				CatchableException<A, B, F, E, D, C>,
				CatchableException<A, C, B, D, E, F>,
				CatchableException<A, C, B, D, F, E>,
				CatchableException<A, C, B, E, D, F>,
				CatchableException<A, C, B, E, F, D>,
				CatchableException<A, C, B, F, D, E>,
				CatchableException<A, C, B, F, E, D>,
				CatchableException<A, C, D, B, E, F>,
				CatchableException<A, C, D, B, F, E>,
				CatchableException<A, C, D, E, B, F>,
				CatchableException<A, C, D, E, F, B>,
				CatchableException<A, C, D, F, B, E>,
				CatchableException<A, C, D, F, E, B>,
				CatchableException<A, C, E, B, D, F>,
				CatchableException<A, C, E, B, F, D>,
				CatchableException<A, C, E, D, B, F>,
				CatchableException<A, C, E, D, F, B>,
				CatchableException<A, C, E, F, B, D>,
				CatchableException<A, C, E, F, D, B>,
				CatchableException<A, C, F, B, D, E>,
				CatchableException<A, C, F, B, E, D>,
				CatchableException<A, C, F, D, B, E>,
				CatchableException<A, C, F, D, E, B>,
				CatchableException<A, C, F, E, B, D>,
				CatchableException<A, C, F, E, D, B>,
				CatchableException<A, D, B, C, E, F>,
				CatchableException<A, D, B, C, F, E>,
				CatchableException<A, D, B, E, C, F>,
				CatchableException<A, D, B, E, F, C>,
				CatchableException<A, D, B, F, C, E>,
				CatchableException<A, D, B, F, E, C>,
				CatchableException<A, D, C, B, E, F>,
				CatchableException<A, D, C, B, F, E>,
				CatchableException<A, D, C, E, B, F>,
				CatchableException<A, D, C, E, F, B>,
				CatchableException<A, D, C, F, B, E>,
				CatchableException<A, D, C, F, E, B>,
				CatchableException<A, D, E, B, C, F>,
				CatchableException<A, D, E, B, F, C>,
				CatchableException<A, D, E, C, B, F>,
				CatchableException<A, D, E, C, F, B>,
				CatchableException<A, D, E, F, B, C>,
				CatchableException<A, D, E, F, C, B>,
				CatchableException<A, D, F, B, C, E>,
				CatchableException<A, D, F, B, E, C>,
				CatchableException<A, D, F, C, B, E>,
				CatchableException<A, D, F, C, E, B>,
				CatchableException<A, D, F, E, B, C>,
				CatchableException<A, D, F, E, C, B>,
				CatchableException<A, E, B, C, D, F>,
				CatchableException<A, E, B, C, F, D>,
				CatchableException<A, E, B, D, C, F>,
				CatchableException<A, E, B, D, F, C>,
				CatchableException<A, E, B, F, C, D>,
				CatchableException<A, E, B, F, D, C>,
				CatchableException<A, E, C, B, D, F>,
				CatchableException<A, E, C, B, F, D>,
				CatchableException<A, E, C, D, B, F>,
				CatchableException<A, E, C, D, F, B>,
				CatchableException<A, E, C, F, B, D>,
				CatchableException<A, E, C, F, D, B>,
				CatchableException<A, E, D, B, C, F>,
				CatchableException<A, E, D, B, F, C>,
				CatchableException<A, E, D, C, B, F>,
				CatchableException<A, E, D, C, F, B>,
				CatchableException<A, E, D, F, B, C>,
				CatchableException<A, E, D, F, C, B>,
				CatchableException<A, E, F, B, C, D>,
				CatchableException<A, E, F, B, D, C>,
				CatchableException<A, E, F, C, B, D>,
				CatchableException<A, E, F, C, D, B>,
				CatchableException<A, E, F, D, B, C>,
				CatchableException<A, E, F, D, C, B>,
				CatchableException<A, F, B, C, D, E>,
				CatchableException<A, F, B, C, E, D>,
				CatchableException<A, F, B, D, C, E>,
				CatchableException<A, F, B, D, E, C>,
				CatchableException<A, F, B, E, C, D>,
				CatchableException<A, F, B, E, D, C>,
				CatchableException<A, F, C, B, D, E>,
				CatchableException<A, F, C, B, E, D>,
				CatchableException<A, F, C, D, B, E>,
				CatchableException<A, F, C, D, E, B>,
				CatchableException<A, F, C, E, B, D>,
				CatchableException<A, F, C, E, D, B>,
				CatchableException<A, F, D, B, C, E>,
				CatchableException<A, F, D, B, E, C>,
				CatchableException<A, F, D, C, B, E>,
				CatchableException<A, F, D, C, E, B>,
				CatchableException<A, F, D, E, B, C>,
				CatchableException<A, F, D, E, C, B>,
				CatchableException<A, F, E, B, C, D>,
				CatchableException<A, F, E, B, D, C>,
				CatchableException<A, F, E, C, B, D>,
				CatchableException<A, F, E, C, D, B>,
				CatchableException<A, F, E, D, B, C>,
				CatchableException<A, F, E, D, C, B>,
				CatchableException<B, A, C, D, E, F>,
				CatchableException<B, A, C, D, F, E>,
				CatchableException<B, A, C, E, D, F>,
				CatchableException<B, A, C, E, F, D>,
				CatchableException<B, A, C, F, D, E>,
				CatchableException<B, A, C, F, E, D>,
				CatchableException<B, A, D, C, E, F>,
				CatchableException<B, A, D, C, F, E>,
				CatchableException<B, A, D, E, C, F>,
				CatchableException<B, A, D, E, F, C>,
				CatchableException<B, A, D, F, C, E>,
				CatchableException<B, A, D, F, E, C>,
				CatchableException<B, A, E, C, D, F>,
				CatchableException<B, A, E, C, F, D>,
				CatchableException<B, A, E, D, C, F>,
				CatchableException<B, A, E, D, F, C>,
				CatchableException<B, A, E, F, C, D>,
				CatchableException<B, A, E, F, D, C>,
				CatchableException<B, A, F, C, D, E>,
				CatchableException<B, A, F, C, E, D>,
				CatchableException<B, A, F, D, C, E>,
				CatchableException<B, A, F, D, E, C>,
				CatchableException<B, A, F, E, C, D>,
				CatchableException<B, A, F, E, D, C>,
				CatchableException<B, C, A, D, E, F>,
				CatchableException<B, C, A, D, F, E>,
				CatchableException<B, C, A, E, D, F>,
				CatchableException<B, C, A, E, F, D>,
				CatchableException<B, C, A, F, D, E>,
				CatchableException<B, C, A, F, E, D>,
				CatchableException<B, C, D, A, E, F>,
				CatchableException<B, C, D, A, F, E>,
				CatchableException<B, C, D, E, A, F>,
				CatchableException<B, C, D, E, F, A>,
				CatchableException<B, C, D, F, A, E>,
				CatchableException<B, C, D, F, E, A>,
				CatchableException<B, C, E, A, D, F>,
				CatchableException<B, C, E, A, F, D>,
				CatchableException<B, C, E, D, A, F>,
				CatchableException<B, C, E, D, F, A>,
				CatchableException<B, C, E, F, A, D>,
				CatchableException<B, C, E, F, D, A>,
				CatchableException<B, C, F, A, D, E>,
				CatchableException<B, C, F, A, E, D>,
				CatchableException<B, C, F, D, A, E>,
				CatchableException<B, C, F, D, E, A>,
				CatchableException<B, C, F, E, A, D>,
				CatchableException<B, C, F, E, D, A>,
				CatchableException<B, D, A, C, E, F>,
				CatchableException<B, D, A, C, F, E>,
				CatchableException<B, D, A, E, C, F>,
				CatchableException<B, D, A, E, F, C>,
				CatchableException<B, D, A, F, C, E>,
				CatchableException<B, D, A, F, E, C>,
				CatchableException<B, D, C, A, E, F>,
				CatchableException<B, D, C, A, F, E>,
				CatchableException<B, D, C, E, A, F>,
				CatchableException<B, D, C, E, F, A>,
				CatchableException<B, D, C, F, A, E>,
				CatchableException<B, D, C, F, E, A>,
				CatchableException<B, D, E, A, C, F>,
				CatchableException<B, D, E, A, F, C>,
				CatchableException<B, D, E, C, A, F>,
				CatchableException<B, D, E, C, F, A>,
				CatchableException<B, D, E, F, A, C>,
				CatchableException<B, D, E, F, C, A>,
				CatchableException<B, D, F, A, C, E>,
				CatchableException<B, D, F, A, E, C>,
				CatchableException<B, D, F, C, A, E>,
				CatchableException<B, D, F, C, E, A>,
				CatchableException<B, D, F, E, A, C>,
				CatchableException<B, D, F, E, C, A>,
				CatchableException<B, E, A, C, D, F>,
				CatchableException<B, E, A, C, F, D>,
				CatchableException<B, E, A, D, C, F>,
				CatchableException<B, E, A, D, F, C>,
				CatchableException<B, E, A, F, C, D>,
				CatchableException<B, E, A, F, D, C>,
				CatchableException<B, E, C, A, D, F>,
				CatchableException<B, E, C, A, F, D>,
				CatchableException<B, E, C, D, A, F>,
				CatchableException<B, E, C, D, F, A>,
				CatchableException<B, E, C, F, A, D>,
				CatchableException<B, E, C, F, D, A>,
				CatchableException<B, E, D, A, C, F>,
				CatchableException<B, E, D, A, F, C>,
				CatchableException<B, E, D, C, A, F>,
				CatchableException<B, E, D, C, F, A>,
				CatchableException<B, E, D, F, A, C>,
				CatchableException<B, E, D, F, C, A>,
				CatchableException<B, E, F, A, C, D>,
				CatchableException<B, E, F, A, D, C>,
				CatchableException<B, E, F, C, A, D>,
				CatchableException<B, E, F, C, D, A>,
				CatchableException<B, E, F, D, A, C>,
				CatchableException<B, E, F, D, C, A>,
				CatchableException<B, F, A, C, D, E>,
				CatchableException<B, F, A, C, E, D>,
				CatchableException<B, F, A, D, C, E>,
				CatchableException<B, F, A, D, E, C>,
				CatchableException<B, F, A, E, C, D>,
				CatchableException<B, F, A, E, D, C>,
				CatchableException<B, F, C, A, D, E>,
				CatchableException<B, F, C, A, E, D>,
				CatchableException<B, F, C, D, A, E>,
				CatchableException<B, F, C, D, E, A>,
				CatchableException<B, F, C, E, A, D>,
				CatchableException<B, F, C, E, D, A>,
				CatchableException<B, F, D, A, C, E>,
				CatchableException<B, F, D, A, E, C>,
				CatchableException<B, F, D, C, A, E>,
				CatchableException<B, F, D, C, E, A>,
				CatchableException<B, F, D, E, A, C>,
				CatchableException<B, F, D, E, C, A>,
				CatchableException<B, F, E, A, C, D>,
				CatchableException<B, F, E, A, D, C>,
				CatchableException<B, F, E, C, A, D>,
				CatchableException<B, F, E, C, D, A>,
				CatchableException<B, F, E, D, A, C>,
				CatchableException<B, F, E, D, C, A>,
				CatchableException<C, A, B, D, E, F>,
				CatchableException<C, A, B, D, F, E>,
				CatchableException<C, A, B, E, D, F>,
				CatchableException<C, A, B, E, F, D>,
				CatchableException<C, A, B, F, D, E>,
				CatchableException<C, A, B, F, E, D>,
				CatchableException<C, A, D, B, E, F>,
				CatchableException<C, A, D, B, F, E>,
				CatchableException<C, A, D, E, B, F>,
				CatchableException<C, A, D, E, F, B>,
				CatchableException<C, A, D, F, B, E>,
				CatchableException<C, A, D, F, E, B>,
				CatchableException<C, A, E, B, D, F>,
				CatchableException<C, A, E, B, F, D>,
				CatchableException<C, A, E, D, B, F>,
				CatchableException<C, A, E, D, F, B>,
				CatchableException<C, A, E, F, B, D>,
				CatchableException<C, A, E, F, D, B>,
				CatchableException<C, A, F, B, D, E>,
				CatchableException<C, A, F, B, E, D>,
				CatchableException<C, A, F, D, B, E>,
				CatchableException<C, A, F, D, E, B>,
				CatchableException<C, A, F, E, B, D>,
				CatchableException<C, A, F, E, D, B>,
				CatchableException<C, B, A, D, E, F>,
				CatchableException<C, B, A, D, F, E>,
				CatchableException<C, B, A, E, D, F>,
				CatchableException<C, B, A, E, F, D>,
				CatchableException<C, B, A, F, D, E>,
				CatchableException<C, B, A, F, E, D>,
				CatchableException<C, B, D, A, E, F>,
				CatchableException<C, B, D, A, F, E>,
				CatchableException<C, B, D, E, A, F>,
				CatchableException<C, B, D, E, F, A>,
				CatchableException<C, B, D, F, A, E>,
				CatchableException<C, B, D, F, E, A>,
				CatchableException<C, B, E, A, D, F>,
				CatchableException<C, B, E, A, F, D>,
				CatchableException<C, B, E, D, A, F>,
				CatchableException<C, B, E, D, F, A>,
				CatchableException<C, B, E, F, A, D>,
				CatchableException<C, B, E, F, D, A>,
				CatchableException<C, B, F, A, D, E>,
				CatchableException<C, B, F, A, E, D>,
				CatchableException<C, B, F, D, A, E>,
				CatchableException<C, B, F, D, E, A>,
				CatchableException<C, B, F, E, A, D>,
				CatchableException<C, B, F, E, D, A>,
				CatchableException<C, D, A, B, E, F>,
				CatchableException<C, D, A, B, F, E>,
				CatchableException<C, D, A, E, B, F>,
				CatchableException<C, D, A, E, F, B>,
				CatchableException<C, D, A, F, B, E>,
				CatchableException<C, D, A, F, E, B>,
				CatchableException<C, D, B, A, E, F>,
				CatchableException<C, D, B, A, F, E>,
				CatchableException<C, D, B, E, A, F>,
				CatchableException<C, D, B, E, F, A>,
				CatchableException<C, D, B, F, A, E>,
				CatchableException<C, D, B, F, E, A>,
				CatchableException<C, D, E, A, B, F>,
				CatchableException<C, D, E, A, F, B>,
				CatchableException<C, D, E, B, A, F>,
				CatchableException<C, D, E, B, F, A>,
				CatchableException<C, D, E, F, A, B>,
				CatchableException<C, D, E, F, B, A>,
				CatchableException<C, D, F, A, B, E>,
				CatchableException<C, D, F, A, E, B>,
				CatchableException<C, D, F, B, A, E>,
				CatchableException<C, D, F, B, E, A>,
				CatchableException<C, D, F, E, A, B>,
				CatchableException<C, D, F, E, B, A>,
				CatchableException<C, E, A, B, D, F>,
				CatchableException<C, E, A, B, F, D>,
				CatchableException<C, E, A, D, B, F>,
				CatchableException<C, E, A, D, F, B>,
				CatchableException<C, E, A, F, B, D>,
				CatchableException<C, E, A, F, D, B>,
				CatchableException<C, E, B, A, D, F>,
				CatchableException<C, E, B, A, F, D>,
				CatchableException<C, E, B, D, A, F>,
				CatchableException<C, E, B, D, F, A>,
				CatchableException<C, E, B, F, A, D>,
				CatchableException<C, E, B, F, D, A>,
				CatchableException<C, E, D, A, B, F>,
				CatchableException<C, E, D, A, F, B>,
				CatchableException<C, E, D, B, A, F>,
				CatchableException<C, E, D, B, F, A>,
				CatchableException<C, E, D, F, A, B>,
				CatchableException<C, E, D, F, B, A>,
				CatchableException<C, E, F, A, B, D>,
				CatchableException<C, E, F, A, D, B>,
				CatchableException<C, E, F, B, A, D>,
				CatchableException<C, E, F, B, D, A>,
				CatchableException<C, E, F, D, A, B>,
				CatchableException<C, E, F, D, B, A>,
				CatchableException<C, F, A, B, D, E>,
				CatchableException<C, F, A, B, E, D>,
				CatchableException<C, F, A, D, B, E>,
				CatchableException<C, F, A, D, E, B>,
				CatchableException<C, F, A, E, B, D>,
				CatchableException<C, F, A, E, D, B>,
				CatchableException<C, F, B, A, D, E>,
				CatchableException<C, F, B, A, E, D>,
				CatchableException<C, F, B, D, A, E>,
				CatchableException<C, F, B, D, E, A>,
				CatchableException<C, F, B, E, A, D>,
				CatchableException<C, F, B, E, D, A>,
				CatchableException<C, F, D, A, B, E>,
				CatchableException<C, F, D, A, E, B>,
				CatchableException<C, F, D, B, A, E>,
				CatchableException<C, F, D, B, E, A>,
				CatchableException<C, F, D, E, A, B>,
				CatchableException<C, F, D, E, B, A>,
				CatchableException<C, F, E, A, B, D>,
				CatchableException<C, F, E, A, D, B>,
				CatchableException<C, F, E, B, A, D>,
				CatchableException<C, F, E, B, D, A>,
				CatchableException<C, F, E, D, A, B>,
				CatchableException<C, F, E, D, B, A>,
				CatchableException<D, A, B, C, E, F>,
				CatchableException<D, A, B, C, F, E>,
				CatchableException<D, A, B, E, C, F>,
				CatchableException<D, A, B, E, F, C>,
				CatchableException<D, A, B, F, C, E>,
				CatchableException<D, A, B, F, E, C>,
				CatchableException<D, A, C, B, E, F>,
				CatchableException<D, A, C, B, F, E>,
				CatchableException<D, A, C, E, B, F>,
				CatchableException<D, A, C, E, F, B>,
				CatchableException<D, A, C, F, B, E>,
				CatchableException<D, A, C, F, E, B>,
				CatchableException<D, A, E, B, C, F>,
				CatchableException<D, A, E, B, F, C>,
				CatchableException<D, A, E, C, B, F>,
				CatchableException<D, A, E, C, F, B>,
				CatchableException<D, A, E, F, B, C>,
				CatchableException<D, A, E, F, C, B>,
				CatchableException<D, A, F, B, C, E>,
				CatchableException<D, A, F, B, E, C>,
				CatchableException<D, A, F, C, B, E>,
				CatchableException<D, A, F, C, E, B>,
				CatchableException<D, A, F, E, B, C>,
				CatchableException<D, A, F, E, C, B>,
				CatchableException<D, B, A, C, E, F>,
				CatchableException<D, B, A, C, F, E>,
				CatchableException<D, B, A, E, C, F>,
				CatchableException<D, B, A, E, F, C>,
				CatchableException<D, B, A, F, C, E>,
				CatchableException<D, B, A, F, E, C>,
				CatchableException<D, B, C, A, E, F>,
				CatchableException<D, B, C, A, F, E>,
				CatchableException<D, B, C, E, A, F>,
				CatchableException<D, B, C, E, F, A>,
				CatchableException<D, B, C, F, A, E>,
				CatchableException<D, B, C, F, E, A>,
				CatchableException<D, B, E, A, C, F>,
				CatchableException<D, B, E, A, F, C>,
				CatchableException<D, B, E, C, A, F>,
				CatchableException<D, B, E, C, F, A>,
				CatchableException<D, B, E, F, A, C>,
				CatchableException<D, B, E, F, C, A>,
				CatchableException<D, B, F, A, C, E>,
				CatchableException<D, B, F, A, E, C>,
				CatchableException<D, B, F, C, A, E>,
				CatchableException<D, B, F, C, E, A>,
				CatchableException<D, B, F, E, A, C>,
				CatchableException<D, B, F, E, C, A>,
				CatchableException<D, C, A, B, E, F>,
				CatchableException<D, C, A, B, F, E>,
				CatchableException<D, C, A, E, B, F>,
				CatchableException<D, C, A, E, F, B>,
				CatchableException<D, C, A, F, B, E>,
				CatchableException<D, C, A, F, E, B>,
				CatchableException<D, C, B, A, E, F>,
				CatchableException<D, C, B, A, F, E>,
				CatchableException<D, C, B, E, A, F>,
				CatchableException<D, C, B, E, F, A>,
				CatchableException<D, C, B, F, A, E>,
				CatchableException<D, C, B, F, E, A>,
				CatchableException<D, C, E, A, B, F>,
				CatchableException<D, C, E, A, F, B>,
				CatchableException<D, C, E, B, A, F>,
				CatchableException<D, C, E, B, F, A>,
				CatchableException<D, C, E, F, A, B>,
				CatchableException<D, C, E, F, B, A>,
				CatchableException<D, C, F, A, B, E>,
				CatchableException<D, C, F, A, E, B>,
				CatchableException<D, C, F, B, A, E>,
				CatchableException<D, C, F, B, E, A>,
				CatchableException<D, C, F, E, A, B>,
				CatchableException<D, C, F, E, B, A>,
				CatchableException<D, E, A, B, C, F>,
				CatchableException<D, E, A, B, F, C>,
				CatchableException<D, E, A, C, B, F>,
				CatchableException<D, E, A, C, F, B>,
				CatchableException<D, E, A, F, B, C>,
				CatchableException<D, E, A, F, C, B>,
				CatchableException<D, E, B, A, C, F>,
				CatchableException<D, E, B, A, F, C>,
				CatchableException<D, E, B, C, A, F>,
				CatchableException<D, E, B, C, F, A>,
				CatchableException<D, E, B, F, A, C>,
				CatchableException<D, E, B, F, C, A>,
				CatchableException<D, E, C, A, B, F>,
				CatchableException<D, E, C, A, F, B>,
				CatchableException<D, E, C, B, A, F>,
				CatchableException<D, E, C, B, F, A>,
				CatchableException<D, E, C, F, A, B>,
				CatchableException<D, E, C, F, B, A>,
				CatchableException<D, E, F, A, B, C>,
				CatchableException<D, E, F, A, C, B>,
				CatchableException<D, E, F, B, A, C>,
				CatchableException<D, E, F, B, C, A>,
				CatchableException<D, E, F, C, A, B>,
				CatchableException<D, E, F, C, B, A>,
				CatchableException<D, F, A, B, C, E>,
				CatchableException<D, F, A, B, E, C>,
				CatchableException<D, F, A, C, B, E>,
				CatchableException<D, F, A, C, E, B>,
				CatchableException<D, F, A, E, B, C>,
				CatchableException<D, F, A, E, C, B>,
				CatchableException<D, F, B, A, C, E>,
				CatchableException<D, F, B, A, E, C>,
				CatchableException<D, F, B, C, A, E>,
				CatchableException<D, F, B, C, E, A>,
				CatchableException<D, F, B, E, A, C>,
				CatchableException<D, F, B, E, C, A>,
				CatchableException<D, F, C, A, B, E>,
				CatchableException<D, F, C, A, E, B>,
				CatchableException<D, F, C, B, A, E>,
				CatchableException<D, F, C, B, E, A>,
				CatchableException<D, F, C, E, A, B>,
				CatchableException<D, F, C, E, B, A>,
				CatchableException<D, F, E, A, B, C>,
				CatchableException<D, F, E, A, C, B>,
				CatchableException<D, F, E, B, A, C>,
				CatchableException<D, F, E, B, C, A>,
				CatchableException<D, F, E, C, A, B>,
				CatchableException<D, F, E, C, B, A>,
				CatchableException<E, A, B, C, D, F>,
				CatchableException<E, A, B, C, F, D>,
				CatchableException<E, A, B, D, C, F>,
				CatchableException<E, A, B, D, F, C>,
				CatchableException<E, A, B, F, C, D>,
				CatchableException<E, A, B, F, D, C>,
				CatchableException<E, A, C, B, D, F>,
				CatchableException<E, A, C, B, F, D>,
				CatchableException<E, A, C, D, B, F>,
				CatchableException<E, A, C, D, F, B>,
				CatchableException<E, A, C, F, B, D>,
				CatchableException<E, A, C, F, D, B>,
				CatchableException<E, A, D, B, C, F>,
				CatchableException<E, A, D, B, F, C>,
				CatchableException<E, A, D, C, B, F>,
				CatchableException<E, A, D, C, F, B>,
				CatchableException<E, A, D, F, B, C>,
				CatchableException<E, A, D, F, C, B>,
				CatchableException<E, A, F, B, C, D>,
				CatchableException<E, A, F, B, D, C>,
				CatchableException<E, A, F, C, B, D>,
				CatchableException<E, A, F, C, D, B>,
				CatchableException<E, A, F, D, B, C>,
				CatchableException<E, A, F, D, C, B>,
				CatchableException<E, B, A, C, D, F>,
				CatchableException<E, B, A, C, F, D>,
				CatchableException<E, B, A, D, C, F>,
				CatchableException<E, B, A, D, F, C>,
				CatchableException<E, B, A, F, C, D>,
				CatchableException<E, B, A, F, D, C>,
				CatchableException<E, B, C, A, D, F>,
				CatchableException<E, B, C, A, F, D>,
				CatchableException<E, B, C, D, A, F>,
				CatchableException<E, B, C, D, F, A>,
				CatchableException<E, B, C, F, A, D>,
				CatchableException<E, B, C, F, D, A>,
				CatchableException<E, B, D, A, C, F>,
				CatchableException<E, B, D, A, F, C>,
				CatchableException<E, B, D, C, A, F>,
				CatchableException<E, B, D, C, F, A>,
				CatchableException<E, B, D, F, A, C>,
				CatchableException<E, B, D, F, C, A>,
				CatchableException<E, B, F, A, C, D>,
				CatchableException<E, B, F, A, D, C>,
				CatchableException<E, B, F, C, A, D>,
				CatchableException<E, B, F, C, D, A>,
				CatchableException<E, B, F, D, A, C>,
				CatchableException<E, B, F, D, C, A>,
				CatchableException<E, C, A, B, D, F>,
				CatchableException<E, C, A, B, F, D>,
				CatchableException<E, C, A, D, B, F>,
				CatchableException<E, C, A, D, F, B>,
				CatchableException<E, C, A, F, B, D>,
				CatchableException<E, C, A, F, D, B>,
				CatchableException<E, C, B, A, D, F>,
				CatchableException<E, C, B, A, F, D>,
				CatchableException<E, C, B, D, A, F>,
				CatchableException<E, C, B, D, F, A>,
				CatchableException<E, C, B, F, A, D>,
				CatchableException<E, C, B, F, D, A>,
				CatchableException<E, C, D, A, B, F>,
				CatchableException<E, C, D, A, F, B>,
				CatchableException<E, C, D, B, A, F>,
				CatchableException<E, C, D, B, F, A>,
				CatchableException<E, C, D, F, A, B>,
				CatchableException<E, C, D, F, B, A>,
				CatchableException<E, C, F, A, B, D>,
				CatchableException<E, C, F, A, D, B>,
				CatchableException<E, C, F, B, A, D>,
				CatchableException<E, C, F, B, D, A>,
				CatchableException<E, C, F, D, A, B>,
				CatchableException<E, C, F, D, B, A>,
				CatchableException<E, D, A, B, C, F>,
				CatchableException<E, D, A, B, F, C>,
				CatchableException<E, D, A, C, B, F>,
				CatchableException<E, D, A, C, F, B>,
				CatchableException<E, D, A, F, B, C>,
				CatchableException<E, D, A, F, C, B>,
				CatchableException<E, D, B, A, C, F>,
				CatchableException<E, D, B, A, F, C>,
				CatchableException<E, D, B, C, A, F>,
				CatchableException<E, D, B, C, F, A>,
				CatchableException<E, D, B, F, A, C>,
				CatchableException<E, D, B, F, C, A>,
				CatchableException<E, D, C, A, B, F>,
				CatchableException<E, D, C, A, F, B>,
				CatchableException<E, D, C, B, A, F>,
				CatchableException<E, D, C, B, F, A>,
				CatchableException<E, D, C, F, A, B>,
				CatchableException<E, D, C, F, B, A>,
				CatchableException<E, D, F, A, B, C>,
				CatchableException<E, D, F, A, C, B>,
				CatchableException<E, D, F, B, A, C>,
				CatchableException<E, D, F, B, C, A>,
				CatchableException<E, D, F, C, A, B>,
				CatchableException<E, D, F, C, B, A>,
				CatchableException<E, F, A, B, C, D>,
				CatchableException<E, F, A, B, D, C>,
				CatchableException<E, F, A, C, B, D>,
				CatchableException<E, F, A, C, D, B>,
				CatchableException<E, F, A, D, B, C>,
				CatchableException<E, F, A, D, C, B>,
				CatchableException<E, F, B, A, C, D>,
				CatchableException<E, F, B, A, D, C>,
				CatchableException<E, F, B, C, A, D>,
				CatchableException<E, F, B, C, D, A>,
				CatchableException<E, F, B, D, A, C>,
				CatchableException<E, F, B, D, C, A>,
				CatchableException<E, F, C, A, B, D>,
				CatchableException<E, F, C, A, D, B>,
				CatchableException<E, F, C, B, A, D>,
				CatchableException<E, F, C, B, D, A>,
				CatchableException<E, F, C, D, A, B>,
				CatchableException<E, F, C, D, B, A>,
				CatchableException<E, F, D, A, B, C>,
				CatchableException<E, F, D, A, C, B>,
				CatchableException<E, F, D, B, A, C>,
				CatchableException<E, F, D, B, C, A>,
				CatchableException<E, F, D, C, A, B>,
				CatchableException<E, F, D, C, B, A>,
				CatchableException<F, A, B, C, D, E>,
				CatchableException<F, A, B, C, E, D>,
				CatchableException<F, A, B, D, C, E>,
				CatchableException<F, A, B, D, E, C>,
				CatchableException<F, A, B, E, C, D>,
				CatchableException<F, A, B, E, D, C>,
				CatchableException<F, A, C, B, D, E>,
				CatchableException<F, A, C, B, E, D>,
				CatchableException<F, A, C, D, B, E>,
				CatchableException<F, A, C, D, E, B>,
				CatchableException<F, A, C, E, B, D>,
				CatchableException<F, A, C, E, D, B>,
				CatchableException<F, A, D, B, C, E>,
				CatchableException<F, A, D, B, E, C>,
				CatchableException<F, A, D, C, B, E>,
				CatchableException<F, A, D, C, E, B>,
				CatchableException<F, A, D, E, B, C>,
				CatchableException<F, A, D, E, C, B>,
				CatchableException<F, A, E, B, C, D>,
				CatchableException<F, A, E, B, D, C>,
				CatchableException<F, A, E, C, B, D>,
				CatchableException<F, A, E, C, D, B>,
				CatchableException<F, A, E, D, B, C>,
				CatchableException<F, A, E, D, C, B>,
				CatchableException<F, B, A, C, D, E>,
				CatchableException<F, B, A, C, E, D>,
				CatchableException<F, B, A, D, C, E>,
				CatchableException<F, B, A, D, E, C>,
				CatchableException<F, B, A, E, C, D>,
				CatchableException<F, B, A, E, D, C>,
				CatchableException<F, B, C, A, D, E>,
				CatchableException<F, B, C, A, E, D>,
				CatchableException<F, B, C, D, A, E>,
				CatchableException<F, B, C, D, E, A>,
				CatchableException<F, B, C, E, A, D>,
				CatchableException<F, B, C, E, D, A>,
				CatchableException<F, B, D, A, C, E>,
				CatchableException<F, B, D, A, E, C>,
				CatchableException<F, B, D, C, A, E>,
				CatchableException<F, B, D, C, E, A>,
				CatchableException<F, B, D, E, A, C>,
				CatchableException<F, B, D, E, C, A>,
				CatchableException<F, B, E, A, C, D>,
				CatchableException<F, B, E, A, D, C>,
				CatchableException<F, B, E, C, A, D>,
				CatchableException<F, B, E, C, D, A>,
				CatchableException<F, B, E, D, A, C>,
				CatchableException<F, B, E, D, C, A>,
				CatchableException<F, C, A, B, D, E>,
				CatchableException<F, C, A, B, E, D>,
				CatchableException<F, C, A, D, B, E>,
				CatchableException<F, C, A, D, E, B>,
				CatchableException<F, C, A, E, B, D>,
				CatchableException<F, C, A, E, D, B>,
				CatchableException<F, C, B, A, D, E>,
				CatchableException<F, C, B, A, E, D>,
				CatchableException<F, C, B, D, A, E>,
				CatchableException<F, C, B, D, E, A>,
				CatchableException<F, C, B, E, A, D>,
				CatchableException<F, C, B, E, D, A>,
				CatchableException<F, C, D, A, B, E>,
				CatchableException<F, C, D, A, E, B>,
				CatchableException<F, C, D, B, A, E>,
				CatchableException<F, C, D, B, E, A>,
				CatchableException<F, C, D, E, A, B>,
				CatchableException<F, C, D, E, B, A>,
				CatchableException<F, C, E, A, B, D>,
				CatchableException<F, C, E, A, D, B>,
				CatchableException<F, C, E, B, A, D>,
				CatchableException<F, C, E, B, D, A>,
				CatchableException<F, C, E, D, A, B>,
				CatchableException<F, C, E, D, B, A>,
				CatchableException<F, D, A, B, C, E>,
				CatchableException<F, D, A, B, E, C>,
				CatchableException<F, D, A, C, B, E>,
				CatchableException<F, D, A, C, E, B>,
				CatchableException<F, D, A, E, B, C>,
				CatchableException<F, D, A, E, C, B>,
				CatchableException<F, D, B, A, C, E>,
				CatchableException<F, D, B, A, E, C>,
				CatchableException<F, D, B, C, A, E>,
				CatchableException<F, D, B, C, E, A>,
				CatchableException<F, D, B, E, A, C>,
				CatchableException<F, D, B, E, C, A>,
				CatchableException<F, D, C, A, B, E>,
				CatchableException<F, D, C, A, E, B>,
				CatchableException<F, D, C, B, A, E>,
				CatchableException<F, D, C, B, E, A>,
				CatchableException<F, D, C, E, A, B>,
				CatchableException<F, D, C, E, B, A>,
				CatchableException<F, D, E, A, B, C>,
				CatchableException<F, D, E, A, C, B>,
				CatchableException<F, D, E, B, A, C>,
				CatchableException<F, D, E, B, C, A>,
				CatchableException<F, D, E, C, A, B>,
				CatchableException<F, D, E, C, B, A>,
				CatchableException<F, E, A, B, C, D>,
				CatchableException<F, E, A, B, D, C>,
				CatchableException<F, E, A, C, B, D>,
				CatchableException<F, E, A, C, D, B>,
				CatchableException<F, E, A, D, B, C>,
				CatchableException<F, E, A, D, C, B>,
				CatchableException<F, E, B, A, C, D>,
				CatchableException<F, E, B, A, D, C>,
				CatchableException<F, E, B, C, A, D>,
				CatchableException<F, E, B, C, D, A>,
				CatchableException<F, E, B, D, A, C>,
				CatchableException<F, E, B, D, C, A>,
				CatchableException<F, E, C, A, B, D>,
				CatchableException<F, E, C, A, D, B>,
				CatchableException<F, E, C, B, A, D>,
				CatchableException<F, E, C, B, D, A>,
				CatchableException<F, E, C, D, A, B>,
				CatchableException<F, E, C, D, B, A>,
				CatchableException<F, E, D, A, B, C>,
				CatchableException<F, E, D, A, C, B>,
				CatchableException<F, E, D, B, A, C>,
				CatchableException<F, E, D, B, C, A>,
				CatchableException<F, E, D, C, A, B>,
				CatchableException<F, E, D, C, B, A>
			{
				BindTaggedException() {}
				explicit BindTaggedException(const std::string &what) :
					BasicException(what) {}
			};
			///@}

			/**
			 * @defgroup UnpackTaggedException
			 * @{
			 */
			/**
			 * @class UnpackTaggedException
			 *
			 * Part of the implementation of @c Exception.
			 *
			 * This class unpacks the tags from a @c Loki::Typelist into
			 * template arguments for @c BindTaggedException.
			 */
			template <typename, typename...>
				struct UnpackTaggedException;
			template <typename Head, typename Tail, typename... Tags>
				struct UnpackTaggedException<Loki::Typelist<Head, Tail>, Tags...>
			{
				typedef typename UnpackTaggedException<Tail, Head, Tags...>::Result Result;
			};
			template <typename... Tags>
				struct UnpackTaggedException<Loki::NullType, Tags...>
			{
				typedef BindTaggedException<Tags...> Result;
			};
			///@}
		}

		/**
		 * @defgroup Exception
		 * @{
		 */
		/**
		 * @class Exception
		 *
		 * A tagged exception class, for use in @c throw statements.
		 *
		 * Each tag represents a different aspect of the error condition.
		 *
		 * Tags can be provided as template arguments in any combination of
		 * individual tags or @c Loki::Typelist sequences of tags.  Duplicate
		 * tags are removed.
		 */
		template <typename... Tags>
			struct Exception :
			Exception<typename util::MakeLokiTypelist<Tags...>::Result>
		{
			Exception() {}
			explicit Exception(const std::string &what) :
				Exception<typename util::MakeLokiTypelist<Tags...>::Result>(what) {}
		};
		template <typename Head, typename Tail>
			struct Exception<Loki::Typelist<Head, Tail>> :
			detail::UnpackTaggedException<typename Loki::TL::NoDuplicates<Loki::Typelist<Head, Tail>>::Result>::Result
		{
			typedef Loki::Typelist<Head, Tail> Tags;

			Exception() {}
			explicit Exception(const std::string &what) :
				detail::UnpackTaggedException<typename Loki::TL::NoDuplicates<Loki::Typelist<Head, Tail>>::Result>::Result(what) {}
		};
		///@}
	}
}

#endif
